import 'dart:convert';
import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:share_plus/share_plus.dart';
import 'package:url_launcher/url_launcher.dart';
import 'package:suraksha_women_safety_app/core/network/backend_url_resolver.dart';
import 'package:suraksha_women_safety_app/features/auth/auth_provider.dart';
import 'package:suraksha_women_safety_app/features/auth/login_screen.dart';
import 'package:suraksha_women_safety_app/features/cybercrime/cybercrime_constants.dart';
import 'package:suraksha_women_safety_app/features/cybercrime/models/cybercrime_models.dart';
import 'package:suraksha_women_safety_app/localization/app_localizations.dart';

void showCyberSnack(BuildContext context, String message) {
  if (!context.mounted) return;
  ScaffoldMessenger.of(context).showSnackBar(
    SnackBar(
      content: Text(message),
      behavior: SnackBarBehavior.floating,
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
    ),
  );
}

Future<bool> handleCyberAuthError(
  BuildContext context,
  WidgetRef ref,
  DioException error,
) async {
  if (error.response?.statusCode != 401) return false;
  await ref.read(authProvider.notifier).logout();
  if (!context.mounted) return true;
  showCyberSnack(
    context,
    AppLocalizations.of(context).t('sessionExpiredSignIn'),
  );
  await Navigator.of(context).pushAndRemoveUntil(
    MaterialPageRoute(builder: (_) => const LoginScreen(redirectToCyber: true)),
    (_) => false,
  );
  return true;
}

String friendlyCyberError(BuildContext context, DioException error) {
  final status = error.response?.statusCode;
  final data = error.response?.data;
  final message = data is Map ? data['message']?.toString() : null;
  if (message != null && message.isNotEmpty) return message;
  final l10n = AppLocalizations.of(context);
  if (status == 401) return l10n.t('loginRequiredCyber');
  if (status == 413) return l10n.t('fileTooLarge10Mb');
  if (BackendUrlResolver.isConnectionError(error)) {
    return l10n.t('cannotReachServer');
  }
  return l10n.t('networkServerIssue');
}

ScamAnalysisResult localAnalyze(String text, String question, List<String> links) {
  final input = '$text $question ${links.join(' ')}'.toLowerCase();
  var score = 0;
  final reasons = <String>[];
  if (RegExp(r'otp|password|pin|cvv').hasMatch(input)) {
    score += 35;
    reasons.add('Sensitive credential request found.');
  }
  if (RegExp(r'upi|refund|kyc|account.*block').hasMatch(input)) {
    score += 25;
    reasons.add('Payment or account pressure indicators found.');
  }
  if (RegExp(r'blackmail|morphed|leak|viral').hasMatch(input)) {
    score += 35;
    reasons.add('Blackmail/extortion indicators found.');
  }
  final level = score >= 45 ? 'HIGH' : score >= 20 ? 'MEDIUM' : 'LOW';
  return ScamAnalysisResult(
    riskLevel: level,
    threatSummary: reasons.isEmpty ? 'No strong local indicators found.' : reasons.join(' '),
    recommendedActions: const [
      'Do not share OTP/passwords',
      'Save evidence',
      'Verify from official source',
    ],
    safetyTips: const [
      'Never pay blackmailers',
      'Report financial fraud on 1930',
      'Block suspicious senders',
    ],
    analysisSource: 'offline-heuristic',
  );
}

Future<void> shareReportPdf(BuildContext context, CyberReportResult report) async {
  final encoded = report.pdfBase64;
  if (encoded == null || encoded.isEmpty) {
    showCyberSnack(context, AppLocalizations.of(context).t('reportSummaryUnavailable'));
    return;
  }
  try {
    final bytes = base64Decode(encoded);
    final dir = await getTemporaryDirectory();
    final safeId = report.id.replaceAll(RegExp(r'[^a-zA-Z0-9_-]'), '');
    final file = File('${dir.path}/suraksha_cyber_complaint_$safeId.pdf');
    await file.writeAsBytes(bytes, flush: true);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf', name: file.uri.pathSegments.last)],
      subject: 'Suraksha cyber crime complaint',
      text: 'Cyber crime complaint PDF generated by Suraksha.',
    );
  } catch (_) {
    if (context.mounted) {
      showCyberSnack(context, AppLocalizations.of(context).t('couldNotSharePdf'));
    }
  }
}

Future<void> shareDownloadedEvidence(
  BuildContext context,
  DownloadedEvidence downloaded,
) async {
  final dir = await getTemporaryDirectory();
  final safeName = downloaded.fileName.replaceAll(RegExp(r'[^\w.-]+'), '_');
  final file = File('${dir.path}/$safeName');
  await file.writeAsBytes(downloaded.bytes, flush: true);
  await Share.shareXFiles(
    [XFile(file.path, mimeType: downloaded.mimeType, name: safeName)],
    subject: 'Suraksha evidence export',
    text: 'Decrypted evidence exported from Suraksha vault.',
  );
}

Future<void> shareVaultExport(
  BuildContext context,
  Map<String, dynamic> payload,
) async {
  try {
    final dir = await getTemporaryDirectory();
    final stamp = DateTime.now().toIso8601String().replaceAll(':', '-');
    final file = File('${dir.path}/suraksha_evidence_package_$stamp.json');
    const encoder = JsonEncoder.withIndent('  ');
    await file.writeAsString(encoder.convert(payload), flush: true);
    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/json', name: file.uri.pathSegments.last)],
      subject: 'Suraksha evidence package',
      text: 'Encrypted evidence package metadata exported from Suraksha.',
    );
  } catch (_) {
    if (context.mounted) {
      showCyberSnack(context, AppLocalizations.of(context).t('couldNotExportEvidence'));
    }
  }
}

Future<bool> requestGalleryPermission() async {
  final status = await Permission.photos.request();
  if (status.isGranted) return true;
  final storage = await Permission.storage.request();
  return storage.isGranted;
}

Future<bool> requestStoragePermission() async {
  final photos = await Permission.photos.request();
  if (photos.isGranted) return true;
  final storage = await Permission.storage.request();
  return storage.isGranted;
}

const fallbackLearningTopics = [
  LearningTopic(
    id: 'password',
    title: 'Password Safety',
    summary: 'Create strong passwords and protect recovery channels.',
    tips: ['Use a password manager.', 'Enable two-factor authentication.', 'Do not reuse passwords.'],
    quiz: [
      QuizQuestion(question: 'Is password reuse safe?', options: ['No', 'Yes'], answerIndex: 0),
    ],
  ),
  LearningTopic(
    id: 'dating',
    title: 'Online Dating Safety',
    summary: 'Recognize coercion, fake identities and image-based abuse risks.',
    tips: ['Video verify carefully.', 'Do not share intimate media.', 'Meet only in public places.'],
    quiz: [
      QuizQuestion(question: 'Should you send money to a new online match?', options: ['No', 'Yes'], answerIndex: 0),
    ],
  ),
];

const fallbackDeepfakeResources = DeepfakeResources(
  title: 'Deepfake & Morphed Image Emergency Support',
  sections: [
    InfoSection(
      title: 'What are deepfakes?',
      body: 'Manipulated media that can falsely show a person in fake photos, audio or videos.',
    ),
    InfoSection(
      title: 'What to do immediately',
      body: 'Save screenshots, URLs and sender IDs. Do not pay or negotiate. Report to cybercrime.gov.in.',
    ),
    InfoSection(
      title: 'Evidence preservation',
      body: 'Keep original files, timestamps, platform links and transaction details.',
    ),
  ],
  helplines: [
    HelplineEntry(label: 'Cyber Crime Helpline', value: '1930'),
    HelplineEntry(label: 'Police Emergency', value: '100'),
  ],
);

String localizedReportCategory(BuildContext context, String category) {
  return AppLocalizations.of(context).t(CybercrimeConstants.reportCategoryKey(category));
}

String localizedEvidenceCategory(BuildContext context, String category) {
  return AppLocalizations.of(context).t(CybercrimeConstants.evidenceCategoryKey(category));
}

Future<void> dialPhoneNumber(String number) async {
  await launchUrl(Uri(scheme: 'tel', path: number), mode: LaunchMode.externalApplication);
}

Future<void> openExternalLink(String link) async {
  await launchUrl(Uri.parse(link), mode: LaunchMode.externalApplication);
}
