import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const supportedLocales = [Locale('en'), Locale('hi'), Locale('mr')];

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appTitle': 'Suraksha',
      'myProfile': 'My Profile',
      'profileSubtitle':
          'Manage your safety identity, language, and emergency readiness.',
      'profileOverview': 'Profile Overview',
      'profileStatsTitle': 'Your safety snapshot',
      'profileHeroCta': 'Personalize your profile for faster emergency support.',
      'languageSelectionTitle': 'Choose app language',
      'darkMode': 'Dark Mode',
      'darkModeSubtitleOn': 'Dark Bluish Theme',
      'darkModeSubtitleOff': 'Soft Calm Light Theme',
      'language': 'Language',
      'contentLanguage': 'Content language for the app',
      'english': 'English',
      'hindi': 'Hindi',
      'marathi': 'Marathi',
      'editProfileDetails': 'EDIT PROFILE DETAILS',
      'editMedicalProfile': 'EDIT MEDICAL PROFILE',
      'fullName': 'Full Name',
      'email': 'Email',
      'phone': 'Phone Number',
      'relation': 'Relation',
      'name': 'Name',
      'bloodGroup': 'Blood Group',
      'allergies': 'Allergies',
      'medicalConditions': 'Medical Conditions',
      'currentMedications': 'Current Medications',
      'phoneNumber': 'Phone Number',
      'notProvided': 'Not provided',
      'emergencyContacts': 'Emergency Contacts',
      'contactsSaved': 'Contacts Saved',
      'emergencyContactList': 'Emergency Contact List',
      'addEmergencyContact': 'ADD EMERGENCY CONTACT',
      'addNewContact': 'Add new contact',
      'logoutSession': 'LOGOUT SESSION',
      'save': 'Save',
      'cancel': 'Cancel',
      'ok': 'OK',
      'saving': 'Saving...',
      'saved': 'Saved',
      'profileSavedTitle': 'Profile saved',
      'profileSavedMessage': 'Your information is now stored and ready to use.',
      'medicalSavedTitle': 'Medical profile saved',
      'medicalSavedMessage':
          'Your medical details have been updated successfully.',
      'contactSavedTitle': 'Contact saved',
      'contactSavedMessage':
          'Emergency contact details were updated successfully.',
      'draftSavedTitle': 'Draft saved',
      'draftSavedMessage':
          'Your draft has been stored locally on this device.',
      'emergencyServices': 'Emergency Services',
      'communityAlerts': 'Community Alerts',
      'womenHelpline': 'Women Helpline',
      'nearbyServices': 'Nearby Services',
      'nearbyHospitals': 'Nearby Hospitals',
      'policeStations': 'Police Stations',
      'nearbyWashrooms': 'Nearby Washrooms',
      'nearbyBloodBanks': 'Nearby Blood Banks',
      'tapToLoadNearby': 'Tap a button to load nearby real-time services.',
      'noNearbyPlaces': 'No nearby places found in 5 km radius.',
      'safeZoneActive': 'Prioritizing your Safety',
      'helloKaveri': 'Hello, Kaveri',
      'openSafetyMap': 'Open Safety Map',
      'openSafetyMapConfirm': 'Want to see this location on the map?',
      'yes': 'Yes',
      'no': 'No',
      'couldNotOpenDialer': 'Could not open dialer',
      'safeZoneUpdatedNearby': 'Safe zone updated nearby',
      'crowdedAreaWarning': 'Crowded area warning',
      'minsAgo2': '2 mins ago',
      'minsAgo15': '15 mins ago',
      'map': 'Map',
      'medical': 'Medical',
      'cyber': 'Cyber',
      'poshPortal': 'POSH Portal',
    },
    'hi': {
      'appTitle': 'सुरक्षा',
      'myProfile': 'मेरा प्रोफाइल',
      'profileSubtitle':
          'अपनी सुरक्षा पहचान, भाषा और आपातकालीन तैयारी संभालें।',
      'profileOverview': 'प्रोफाइल सारांश',
      'profileStatsTitle': 'आपकी सुरक्षा झलक',
      'profileHeroCta': 'तेज़ सहायता के लिए प्रोफाइल को निजी बनाएं।',
      'languageSelectionTitle': 'ऐप भाषा चुनें',
      'darkMode': 'डार्क मोड',
      'darkModeSubtitleOn': 'डार्क ब्लू थीम',
      'darkModeSubtitleOff': 'हल्की शांत थीम',
      'language': 'भाषा',
      'contentLanguage': 'ऐप की सामग्री की भाषा',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'editProfileDetails': 'प्रोफाइल विवरण संपादित करें',
      'editMedicalProfile': 'मेडिकल प्रोफाइल संपादित करें',
      'fullName': 'पूरा नाम',
      'email': 'ईमेल',
      'phone': 'फोन नंबर',
      'relation': 'संबंध',
      'name': 'नाम',
      'bloodGroup': 'ब्लड ग्रुप',
      'allergies': 'एलर्जी',
      'medicalConditions': 'चिकित्सीय स्थितियां',
      'currentMedications': 'वर्तमान दवाएं',
      'phoneNumber': 'फोन नंबर',
      'notProvided': 'उपलब्ध नहीं',
      'emergencyContacts': 'आपातकालीन संपर्क',
      'contactsSaved': 'संपर्क सहेजे गए',
      'emergencyContactList': 'आपातकालीन संपर्क सूची',
      'addEmergencyContact': 'आपातकालीन संपर्क जोड़ें',
      'addNewContact': 'नया संपर्क जोड़ें',
      'logoutSession': 'लॉगआउट',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'ok': 'ठीक है',
      'saving': 'सहेजा जा रहा है...',
      'saved': 'सहेजा गया',
      'profileSavedTitle': 'प्रोफाइल सहेजा गया',
      'profileSavedMessage': 'आपकी जानकारी सुरक्षित रूप से सहेज ली गई है।',
      'medicalSavedTitle': 'मेडिकल प्रोफाइल सहेजा गया',
      'medicalSavedMessage': 'आपकी मेडिकल जानकारी सफलतापूर्वक अपडेट हो गई है।',
      'contactSavedTitle': 'संपर्क सहेजा गया',
      'contactSavedMessage': 'आपातकालीन संपर्क विवरण सफलतापूर्वक अपडेट हो गए।',
      'draftSavedTitle': 'ड्राफ्ट सहेजा गया',
      'draftSavedMessage': 'आपका ड्राफ्ट इस डिवाइस पर सुरक्षित कर लिया गया है।',
      'emergencyServices': 'आपातकालीन सेवाएं',
      'communityAlerts': 'समुदाय अलर्ट',
      'womenHelpline': 'महिला हेल्पलाइन',
      'nearbyServices': 'नज़दीकी सेवाएं',
      'nearbyHospitals': 'नज़दीकी अस्पताल',
      'policeStations': 'पुलिस स्टेशन',
      'nearbyWashrooms': 'नज़दीकी वॉशरूम',
      'nearbyBloodBanks': 'नज़दीकी ब्लड बैंक',
      'tapToLoadNearby': 'नज़दीकी सेवाएं लोड करने के लिए बटन दबाएं।',
      'noNearbyPlaces': '5 किमी के दायरे में कोई स्थान नहीं मिला।',
      'safeZoneActive': 'सुरक्षा प्राथमिकता',
      'helloKaveri': 'नमस्ते, कावेरी',
      'openSafetyMap': 'सुरक्षा मानचित्र खोलें',
      'openSafetyMapConfirm': 'क्या आप यह स्थान मानचित्र पर देखना चाहते हैं?',
      'yes': 'हाँ',
      'no': 'नहीं',
      'couldNotOpenDialer': 'डायलर नहीं खुल सका',
      'safeZoneUpdatedNearby': 'नज़दीक सुरक्षित क्षेत्र अपडेट हुआ',
      'crowdedAreaWarning': 'भीड़भाड़ क्षेत्र चेतावनी',
      'minsAgo2': '2 मिनट पहले',
      'minsAgo15': '15 मिनट पहले',
      'map': 'मैप',
      'medical': 'मेडिकल',
      'cyber': 'साइबर',
      'poshPortal': 'पॉश पोर्टल',
    },
    'mr': {
      'appTitle': 'सुरक्षा',
      'myProfile': 'माझे प्रोफाइल',
      'profileSubtitle':
          'तुमची सुरक्षा ओळख, भाषा आणि आपत्कालीन तयारी सांभाळा.',
      'profileOverview': 'प्रोफाइल सारांश',
      'profileStatsTitle': 'तुमचा सुरक्षा स्नॅपशॉट',
      'profileHeroCta': 'जलद मदतीसाठी प्रोफाइल वैयक्तिक बनवा.',
      'languageSelectionTitle': 'अॅपची भाषा निवडा',
      'darkMode': 'डार्क मोड',
      'darkModeSubtitleOn': 'डार्क ब्लू थीम',
      'darkModeSubtitleOff': 'हलकी शांत थीम',
      'language': 'भाषा',
      'contentLanguage': 'अॅपमधील मजकुराची भाषा',
      'english': 'इंग्रजी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'editProfileDetails': 'प्रोफाइल तपशील संपादित करा',
      'editMedicalProfile': 'मेडिकल प्रोफाइल संपादित करा',
      'fullName': 'पूर्ण नाव',
      'email': 'ईमेल',
      'phone': 'फोन नंबर',
      'relation': 'नाते',
      'name': 'नाव',
      'bloodGroup': 'ब्लड ग्रुप',
      'allergies': 'अॅलर्जी',
      'medicalConditions': 'आरोग्यविषयक स्थिती',
      'currentMedications': 'सध्याची औषधे',
      'phoneNumber': 'फोन नंबर',
      'notProvided': 'उपलब्ध नाही',
      'emergencyContacts': 'आपत्कालीन संपर्क',
      'contactsSaved': 'संपर्क जतन केले',
      'emergencyContactList': 'आपत्कालीन संपर्क यादी',
      'addEmergencyContact': 'आपत्कालीन संपर्क जोडा',
      'addNewContact': 'नवीन संपर्क जोडा',
      'logoutSession': 'लॉगआउट',
      'save': 'जतन करा',
      'cancel': 'रद्द करा',
      'ok': 'ठीक आहे',
      'saving': 'जतन करत आहे...',
      'saved': 'जतन झाले',
      'profileSavedTitle': 'प्रोफाइल जतन झाले',
      'profileSavedMessage': 'तुमची माहिती सुरक्षितपणे जतन झाली आहे.',
      'medicalSavedTitle': 'मेडिकल प्रोफाइल जतन झाले',
      'medicalSavedMessage':
          'तुमची मेडिकल माहिती यशस्वीरित्या अपडेट झाली आहे.',
      'contactSavedTitle': 'संपर्क जतन झाला',
      'contactSavedMessage':
          'आपत्कालीन संपर्क तपशील यशस्वीरित्या अपडेट झाले आहेत.',
      'draftSavedTitle': 'ड्राफ्ट जतन झाला',
      'draftSavedMessage': 'तुमचा ड्राफ्ट या डिव्हाइसवर सुरक्षित झाला आहे.',
      'emergencyServices': 'आपत्कालीन सेवा',
      'communityAlerts': 'समुदाय सूचना',
      'womenHelpline': 'महिला हेल्पलाइन',
      'nearbyServices': 'जवळच्या सेवा',
      'nearbyHospitals': 'जवळची रुग्णालये',
      'policeStations': 'पोलीस ठाणे',
      'nearbyWashrooms': 'जवळचे वॉशरूम',
      'nearbyBloodBanks': 'जवळच्या रक्तपेढ्या',
      'tapToLoadNearby': 'जवळच्या सेवा लोड करण्यासाठी बटण दाबा.',
      'noNearbyPlaces': '5 किमी परिसरात कोणतीही जागा सापडली नाही.',
      'safeZoneActive': 'सुरक्षा प्राधान्य',
      'helloKaveri': 'नमस्कार, कावेरी',
      'openSafetyMap': 'सुरक्षा नकाशा उघडा',
      'openSafetyMapConfirm': 'हे ठिकाण नकाशावर पाहायचे आहे का?',
      'yes': 'हो',
      'no': 'नाही',
      'couldNotOpenDialer': 'डायलर उघडता आला नाही',
      'safeZoneUpdatedNearby': 'जवळ सुरक्षित क्षेत्र अपडेट झाले',
      'crowdedAreaWarning': 'गर्दीच्या भागाची चेतावणी',
      'minsAgo2': '2 मिनिटांपूर्वी',
      'minsAgo15': '15 मिनिटांपूर्वी',
      'map': 'नकाशा',
      'medical': 'मेडिकल',
      'cyber': 'सायबर',
      'poshPortal': 'POSH पोर्टल',
    },
  };

  String t(String key) {
    final langCode =
        supportedLocales.any((e) => e.languageCode == locale.languageCode)
        ? locale.languageCode
        : 'en';
    return _values[langCode]?[key] ?? _values['en']![key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
