import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const supportedLocales = [Locale('en'), Locale('hi'), Locale('mr')];

  static String _languageCodeFor(Locale locale) {
    final normalizedCode = locale.languageCode.toLowerCase();
    return supportedLocales.any((item) => item.languageCode == normalizedCode)
        ? normalizedCode
        : 'en';
  }

  static final Map<String, Map<String, String>> _values = {
    'en': {
      'appTitle': 'Suraksha',
      'greetingHello': 'Hello',
      'welcomeBack': 'Welcome Back',
      'signInToContinue': 'Sign in to continue your safety journey',
      'emailOrPhone': 'Email or Phone Number',
      'password': 'Password',
      'login': 'LOGIN',
      'emergencyContactsInformed': 'Emergency Contacts Informed',
      'liveLocationSharedWith': 'Live location has been shared with:',
      'fetchingLocation': 'Fetching location...',
      'liveFeedActive': 'Live Feed Active ({time})',
      'startingLiveTransmission': 'Starting live transmission...',
      'liveTransmissionPaused': 'Live transmission paused',
      'emergencyModeActive': 'EMERGENCY MODE ACTIVE',
      'helpOnTheWay': 'Help is on the way. Your live location is being shared.',
      'currentLocation': 'Current Location',
      'status': 'Status',
      'iAmSafeCancelSos': 'I AM SAFE - CANCEL SOS',
      'myProfile': 'My Profile',
      'profileSubtitle':
          'Manage your safety identity, language, and emergency readiness.',
      'profileOverview': 'Profile Overview',
      'profileStatsTitle': 'Your safety snapshot',
      'profileHeroCta':
          'Personalize your profile for faster emergency support.',
      'languageSelectionTitle': 'Choose app language',
      'darkMode': 'Dark Mode',
      'darkModeSubtitleOn': 'Dark Bluish Theme',
      'darkModeSubtitleOff': 'Soft Calm Light Theme',
      'language': 'Language',
      'contentLanguage': 'Content language for the app',
      'english': 'English',
      'hindi': 'Hindi',
      'marathi': 'Marathi',
      'editProfile': 'Edit Profile',
      'editPhoneNumber': 'Edit Phone Number',
      'addEmergencyContactTitle': 'Add Emergency Contact',
      'editEmergencyContactTitle': 'Edit Emergency Contact',
      'editProfileDetails': 'EDIT PROFILE DETAILS',
      'editMedicalProfile': 'EDIT MEDICAL PROFILE',
      'fullName': 'Full Name',
      'email': 'Email',
      'phone': 'Phone Number',
      'relation': 'Relation',
      'name': 'Name',
      'bloodGroup': 'Blood Group',
      'allergies': 'Allergies',
      'medicalConditions': 'Medical Conditions',
      'currentMedications': 'Current Medications',
      'phoneNumber': 'Phone Number',
      'notProvided': 'Not provided',
      'emergencyContacts': 'Emergency Contacts',
      'contactsSaved': 'Contacts Saved',
      'emergencyContactList': 'Emergency Contact List',
      'addEmergencyContact': 'ADD EMERGENCY CONTACT',
      'addNewContact': 'Add new contact',
      'logoutSession': 'LOGOUT SESSION',
      'save': 'Save',
      'cancel': 'Cancel',
      'ok': 'OK',
      'saving': 'Saving...',
      'saved': 'Saved',
      'screamDetection': 'Scream Detection',
      'screamDetectionEnabled': 'Scream detection enabled.',
      'screamDetectionDisabled': 'Scream detection disabled.',
      'screamDetectionEnableFailed': 'Could not enable scream detection.',
      'distressSensitivity': 'Detection sensitivity',
      'distressSensitivitySubtitle':
          'High catches quieter screams; low reduces false alarms.',
      'distressSensitivity_low': 'Low',
      'distressSensitivity_medium': 'Medium',
      'distressSensitivity_high': 'High',
      'distressTestMode': 'Test mode (no SOS)',
      'distressTestModeSubtitle':
          'Detect screams and phrases but never send SOS. Use to verify accuracy.',
      'distressLastHeard': 'Last heard',
      'microphoneSafetyMonitorActive': 'Microphone safety monitor is active.',
      'microphoneSafetyMonitorInactive':
          'Microphone stays off while this is disabled.',
      'impactDetection': 'Impact Detection',
      'impactDetectionEnabled': 'Impact detection enabled.',
      'impactDetectionDisabled': 'Impact detection disabled.',
      'impactDetectionEnableFailed': 'Could not enable impact detection.',
      'motionSensorsActive': 'Motion sensors are watching for sudden impact.',
      'motionSensorsInactive':
          'Motion sensors stay off while this is disabled.',
      'phoneNumberRequired': 'Phone number is required.',
      'nameAndPhoneRequired': 'Name and phone number are required.',
      'duplicatePhoneNumber': 'This phone number is already saved.',
      'savedLocallyRetryLater': 'Saved locally. Server sync will retry later.',
      'photoSavedLocally': 'Photo saved locally.',
      'serverSyncWillRetryLater': 'Server sync will retry later.',
      'profileSavedTitle': 'Profile saved',
      'profileSavedMessage': 'Your information is now stored and ready to use.',
      'medicalSavedTitle': 'Medical profile saved',
      'medicalSavedMessage':
          'Your medical details have been updated successfully.',
      'contactSavedTitle': 'Contact saved',
      'contactSavedMessage':
          'Emergency contact details were updated successfully.',
      'draftSavedTitle': 'Draft saved',
      'draftSavedMessage': 'Your draft has been stored locally on this device.',
      'emergencyServices': 'Emergency Services',
      'communityAlerts': 'Community Alerts',
      'safetyRegionLabel': 'Region',
      'safetyDataDisclaimerTitle': 'Data sources',
      'safetyConfidenceSuffix': 'confidence',
      'safetySourceOpenStreetMap': 'OpenStreetMap',
      'safetySourceSunset': 'Sunset API',
      'safetySourceCrowd': 'Anonymous crowd',
      'safetySourceSurakshaReports': 'Suraksha reports',
      'safetySourceSurakshaEngine': 'Suraksha engine',
      'safetySourceSurakshaCommunity': 'Community verified',
      'safetySourceRegionalGuidance': 'Regional guidance',
      'safetyDimCrime': 'Crime',
      'safetyDimInfrastructure': 'Lighting',
      'safetyDimSupport': 'Support',
      'safetyDimVisibility': 'Visibility',
      'safetyDimTemporal': 'Time',
      'safetySourceGridModel': 'Grid model',
      'safetySourceOpenDataDistrict': 'District open data',
      'safetyUpdatedAgo': 'Updated',
      'aiSummaryFromGemini': 'AI summary (Gemini)',
      'aiSummaryFromTemplate': 'AI summary (offline)',
      'journeySafetyAlerts': 'Journey safety alerts',
      'journeySafetyAlertsSubtitle':
          'Push and in-app alerts when entering higher-risk zones during navigation.',
      'journeyRerouteHint': 'Safer route available',
      'tapForAlerts': 'Tap for alerts',
      'tapRefreshTryAgain': 'Tap refresh to try again',
      'loadingLiveAreaAlerts': 'Loading live area alerts...',
      'checkingTrafficTransportNearbyActivity':
          'Checking traffic, transport and nearby activity',
      'liveAlertsWillAppearHere': 'Live alerts will appear here',
      'keepGpsOnForRealtimeCommunityUpdates':
          'Keep GPS on for realtime community updates',
      'locationRequiredTitle': 'Location required',
      'locationRequiredMessage':
          'Suraksha requires GPS and location permission to work. Please enable them to continue.',
      'locationAutoRefreshMessage':
          'Once location is enabled, services refresh automatically.',
      'retryLocation': 'Retry location setup',
      'womenHelpline': 'Women Helpline',
      'nearbyServices': 'Nearby Services',
      'nearbyHospitals': 'Nearby Hospitals',
      'policeStations': 'Police Stations',
      'nearbyWashrooms': 'Nearby Washrooms',
      'nearbyBloodBanks': 'Nearby Blood Banks',
      'nearbyPharmacies': 'Nearby Pharmacies',
      'tapToLoadNearby': 'Tap a button to load nearby real-time services.',
      'noNearbyPlaces': 'No nearby places found in 5 km radius.',
      'safeZoneActive': 'Prioritizing your Safety',
      'helloKaveri': 'Hello, Kaveri',
      'openSafetyMap': 'Open Safety Map',
      'openSafetyMapConfirm': 'Want to see this location on the map?',
      'mapOpenChoiceTitle': 'Open location',
      'mapOpenChoiceMessage': 'Choose how you want to open this place.',
      'mapOpenChoiceSuraksha': 'Suraksha Map',
      'mapOpenChoiceGoogle': 'Google Maps',
      'yes': 'Yes',
      'no': 'No',
      'couldNotOpenDialer': 'Could not open dialer',
      'policeEmergency': 'Police Emergency',
      'scanningNearbyPlaces': 'Scanning nearby places...',
      'nearbyResultsCount': '{count} nearby results',
      'chooseServiceToScanYourArea':
          'Choose a service below to scan your current area.',
      'cyberCrimeProtection': 'Cyber Crime Protection',
      'aiAssist': 'AI Assist',
      'report': 'Report',
      'vault': 'Vault',
      'learn': 'Learn',
      'deepfake': 'Deepfake',
      'aiScamFraudAssistantTitle': 'AI Scam & Fraud Detection Assistant',
      'pasteEvidenceContext':
          'Paste suspicious messages, links, chats or questions. Attach screenshots as evidence context.',
      'suspiciousMessageLabel': 'Suspicious message, email or chat',
      'pasteFullMessageHereHint': 'Paste the full message here...',
      'suspiciousLinksLabel': 'Suspicious links',
      'urlHint': 'https://example.com, bit.ly/...',
      'askQuestionLabel': 'Ask a question',
      'scamQuestionHint': 'Is this a scam? Is this profile fake?',
      'attachScreenshot': 'Attach screenshot',
      'analyze': 'Analyze',
      'selectIncidentType': 'Select incident type',
      'attachScreenshotsOrProof': 'Attach screenshots or transaction proof',
      'incidentDescription': 'Incident description',
      'incidentDetailsHint':
          'Describe what happened, usernames, amounts, threats, and platforms.',
      'suspectContactLabel': 'Phone/email/profile link',
      'suspectContactHint': 'Suspect contact or profile URL',
      'transactionIdLabel': 'Transaction ID',
      'transactionIdHint': 'UPI/ref no. if financial fraud',
      'incidentTime': 'Incident time: {time}',
      'pdfReady': 'PDF ready',
      'newReport': 'New report',
      'saveDraft': 'Save draft',
      'reportGenerated': 'Report generated.',
      'draftSavedOnline': 'Draft saved online.',
      'couldNotSubmitOnline': 'Could not submit online. Please try again.',
      'secureEvidenceVault': 'Secure Evidence Vault',
      'uploadTagSearchPackageEvidence':
          'Upload, tag, search and package cyber evidence. Backend files are AES encrypted.',
      'takeQuiz': 'Take quiz',
      'progressBadge': '{percent}% complete | Badge: {badge}',
      'cyberDefender': 'Cyber Defender',
      'cyberLearner': 'Cyber Learner',
      'deepfakeSubtitle':
          'Awareness, emergency response, legal guidance and helpline access.',
      'deepfakeWarning':
          'If someone threatens to leak morphed/private media, do not pay or negotiate. Preserve evidence and report quickly.',
      'emergencyActions': 'Emergency actions',
      'call1930': 'Call 1930',
      'police100': 'Police 100',
      'cyberPortal': 'Cyber Portal',
      'uploadEncryptedEvidence': 'Upload encrypted evidence',
      'noFilesSelectedYet': 'No files selected yet.',
      'generate': 'Generate',
      'generatedComplaint': 'Generated complaint',
      'reportSummaryUnavailable': 'Report summary unavailable.',
      'pdfPayloadGenerated':
          'PDF payload generated. Export integration can save/share it from backend response.',
      'evidenceTitleLabel': 'Evidence title',
      'evidenceTitleHint': 'Threat screenshot, UPI proof...',
      'category': 'Category',
      'private': 'Private',
      'tags': 'Tags',
      'tagsHint': 'blackmail, instagram, payment',
      'finish': 'Finish',
      'searchVault': 'Search vault',
      'searchByTitle': 'Search by title',
      'noEvidenceFound':
          'No evidence found. Upload evidence to start your secure vault.',
      'sessionExpiredSignIn': 'Session expired. Please sign in again.',
      'loginRequiredCyber': 'Please login again to use secure cyber features.',
      'fileTooLarge10Mb': 'File is too large. Maximum upload size is 10 MB.',
      'networkServerIssue': 'Network or server issue. Please try again.',
      'couldNotSharePdf': 'Could not share PDF. Please try again.',
      'couldNotExportEvidence': 'Could not export evidence package.',
      'riskLevel': 'Risk Level',
      'recommendedActions': 'Recommended actions',
      'safetyTips': 'Safety tips',
      'encrypted': 'Encrypted',
      'notEncrypted': 'Not encrypted',
      'linkedToReport': 'Linked to report',
      'preview': 'Preview',
      'download': 'Download',
      'delete': 'Delete',
      'noUnlinkedEvidence': 'No unlinked evidence in vault.',
      'minDescriptionChars': 'Add at least 10 characters of incident details.',
      'draftPendingDetails': 'Draft report pending details.',
      'evidenceFilesSecured': '{count} evidence file(s) secured in vault.',
      'vaultEvidenceLinked': '{count} vault item(s) linked to report.',
      'summaryStep': 'Summary',
      'myReports': 'My Reports',
      'noSubmittedReportsYet': 'No submitted reports yet. Generate a complaint to see it here.',
      'draft': 'Draft',
      'pickFromGallery': 'Gallery',
      'pickFile': 'Pick file',
      'attachFromVault': 'From vault',
      'vaultItemsSelected': '{count} vault item(s) selected',
      'uploadingEvidence': 'Uploading evidence...',
      'selectVaultEvidence': 'Select vault evidence',
      'analyzeInputRequired': 'Paste a message, link, question, or attach a screenshot.',
      'clearScreenshot': 'Clear screenshot',
      'screenshotTextExtracted': 'Screenshot text extracted',
      'evidenceEncryptedSaved': 'Evidence encrypted and saved.',
      'uploadFailed': 'Upload failed.',
      'previewFailed': 'Preview failed.',
      'downloadFailed': 'Download failed.',
      'deleteEvidenceTitle': 'Delete evidence?',
      'deleteEvidenceConfirm': 'Remove "{title}" from your secure vault?',
      'evidenceDeleted': 'Evidence deleted.',
      'deleteFailed': 'Delete failed.',
      'exportFailed': 'Export failed.',
      'exportEvidencePackage': 'Export evidence package',
      'filterAll': 'All',
      'filterLinked': 'Linked',
      'filterUnlinked': 'Unlinked',
      'reportDetails': 'Report details',
      'linkedEvidence': 'Linked evidence',
      'noLinkedEvidence': 'No evidence linked to this report yet.',
      'digitalSafetyLearningHub': 'Digital Safety Learning Hub',
      'learningHubSubtitle': 'Build skills for phishing, UPI, privacy, stalking prevention and deepfake response.',
      'cyberSafetyScore': 'Cyber Safety Score',
      'cyberSafetyScoreUpdated': 'Cyber Safety Score: {score}',
      'catFinancialFraud': 'Financial Fraud',
      'catCyberStalking': 'Cyber Stalking',
      'catOnlineBullying': 'Online Bullying',
      'catIdentityTheft': 'Identity Theft',
      'catSocialMediaHarassment': 'Social Media Harassment',
      'catHarassment': 'Harassment',
      'catBlackmail': 'Blackmail',
      'catFakeProfile': 'Fake Profile',
      'catDeepfakeThreat': 'Deepfake Threat',
      'catDeepfakeScam': 'Deepfake Scam',
      'catFakeJobScam': 'Fake Job Scam',
      'catUpiFraud': 'UPI Fraud',
      'catOther': 'Other',
      'evidenceCatAll': 'All',
      'evidenceCatScreenshot': 'Screenshot',
      'evidenceCatAudio': 'Audio',
      'evidenceCatThreatMessage': 'Threat Message',
      'evidenceCatImage': 'Image',
      'evidenceCatTransactionProof': 'Transaction Proof',
      'evidenceCatDocument': 'Document',
      'evidenceCatOther': 'Other',
      'multiSelectNone': 'None selected',
      'multiSelectCount': '{count} selected',
      'filterCategories': 'Filter categories',
      'filterLinkStatus': 'Link status',
      'additionalCategoriesNote': 'Additional incident types',
      'configureServer': 'Configure server',
      'configureServerHint':
          'Enter your PC IP where the backend runs. Example: http://192.168.1.5:5000/api',
      'serverUrlHint': 'http://192.168.1.5:5000/api',
      'serverUrlSaved': 'Server URL saved. Retrying connection...',
      'cannotReachServer':
          'Unable to connect to the server. Please check your internet connection and try again.',
      'fixConnection': 'Retry connection',
      'deepfakeEmergencySupportTitle':
          'Deepfake & Morphed Image Emergency Support',
      'medicalHealthVault': 'Medical Health Vault',
      'keepEmergencyMedicalInformationOrganized':
          'Keep emergency medical information beautifully organized for quick use.',
      'emergencyMedicalId': 'Emergency Medical ID',
      'scanInCaseOfMedicalEmergency': 'Scan in case of medical emergency',
      'medicalProfileSaved': 'Medical profile saved',
      'medicalDetailsReady':
          'Your medical details are ready for emergency use.',
      'savedLocallyOnThisDevice': 'Saved locally on this device.',
      'medicalProfileSavedLocallySyncRetryLater':
          'Medical profile saved locally. Sync will retry later.',
      'certificateDetails': 'Certificate details',
      'issuedOn': 'Issued on {date}',
      'poshCertifiedMessage':
          'You have completed all three quiz levels and demonstrated strong POSH Act knowledge.',
      'validForPoshCertificate':
          'Valid for: POSH Act awareness and workplace safety learning',
      'safeZoneUpdatedNearby': 'Safe zone updated nearby',
      'crowdedAreaWarning': 'Crowded area warning',
      'loadingNearbySafetyPoints': 'Loading nearby safety points...',
      'unableToFetchLocation':
          'Unable to fetch location. Move near open sky and try again.',
      'couldNotFetchYourLocation': 'Could not fetch your location.',
      'youAreHere': 'You are here',
      'surakshaLiveLocationNotificationTitle': 'Suraksha Live Location',
      'surakshaLiveLocationNotificationText':
          'Tracking live location for safety features.',
      'journeyStopped': 'Journey stopped',
      'totalRoute': 'total route',
      'stop': 'Stop',
      'start': 'Start',
      'minsAgo2': '2 mins ago',
      'minsAgo15': '15 mins ago',
      'map': 'Map',
      'medical': 'Medical',
      'cyber': 'Cyber',
      'poshPortal': 'POSH Portal',
      'liveSafetyMapTitle': 'Live Safety Map',
      'locating': 'Locating...',
      'myLocation': 'My Location',
      'refreshNearby': 'Refresh Nearby',
      'retryLiveLocation': 'Retry Live Location',
      'safetyIntelligenceMap': 'Safety Intelligence Map',
      'couldNotFindThatLocation': 'Could not find that location.',
      'couldNotOpenThisPlace': 'Could not open this place.',
      'tryAgain': 'Try again',
      'longPressDropPinPreviewRoute':
          'Long press to drop pin. Tap markers to preview route.',
      'fetchingYourLocation': 'Fetching your current location...',
      'mapWillOpenAroundYou':
          'The map will open directly around you once GPS is ready.',
      'searchLocation': 'Search location...',
      'liveTrackingActive': 'Live tracking active',
      'journeyTrackingActive': 'Journey tracking active',
      'destinationReached': 'Destination reached',
      'selectedDestination': 'Selected destination',
      'calculatingRoute': 'Calculating route',
      'remaining': 'Remaining',
      'routePreview': 'Route preview',
      'liveNavigation': 'Live navigation',
      'followingYourRoute': 'Following your route with live progress',
      'readyWithDistanceAndEstimatedTravelTime':
          'Ready with distance and estimated travel time',
      'calculatingRouteDistance': 'Calculating route distance',
      'covered': 'Covered',
      'eta': 'ETA',
      'selectedLocation': 'Selected Location',
      'customPin': 'Custom Pin',
      'study': 'Study',
      'quizzes': 'Quizzes',
      'complaint': 'Complaint',
      'poshActLearningHub': 'POSH Act Learning Hub',
      'poshStudy1Title': 'What the POSH Act Covers',
      'poshStudy1Bullet1':
          'The POSH Act is the Sexual Harassment of Women at Workplace Act, 2013.',
      'poshStudy1Bullet2':
          'It protects dignity, equality, and safe working conditions.',
      'poshStudy1Bullet3':
          'It applies to public and private workplaces, offices, shops, hospitals, schools, NGOs, transport provided by employer, and work-related visits.',
      'poshStudy1Bullet4':
          'The law covers employees, trainees, interns, contract staff, volunteers, and workplace visitors in the relevant context.',
      'poshStudy1Bullet5':
          'Unwelcome conduct of a sexual nature can be verbal, written, digital, or physical.',
      'poshStudy1Bullet6':
          'Examples include unwanted touching, sexual remarks, sexual messages, repeated harassment, or showing pornography.',
      'poshStudy2Title': 'Complaint Process and IC Handling',
      'poshStudy2Bullet1':
          'The complaint should normally be filed in writing within 3 months of the incident or last incident in a continuing pattern.',
      'poshStudy2Bullet2':
          'The Internal Committee should be properly formed where the workplace has 10 or more employees.',
      'poshStudy2Bullet3':
          'The committee generally includes a senior woman presiding officer, employee members, and an external member familiar with harassment matters.',
      'poshStudy2Bullet4':
          'Conciliation can be used only if the complainant wants it, and it should not be forced.',
      'poshStudy2Bullet5':
          'If no conciliation happens, the IC conducts a formal inquiry with both sides heard fairly.',
      'poshStudy2Bullet6':
          'The process should stay confidential, written, and documented.',
      'poshStudy3Title': 'Evidence, Safety, and Employer Duties',
      'poshStudy3Bullet1':
          'Keep chats, emails, screenshots, call logs, witness names, dates, and location details.',
      'poshStudy3Bullet2':
          'Interim relief can include leave, transfer, no-contact directions, or reporting-line changes if needed for safety.',
      'poshStudy3Bullet3':
          'If the facts also show criminal conduct, a police complaint or FIR can be filed in addition to the POSH process.',
      'poshStudy3Bullet4':
          'Employers should display the policy, train staff, support the IC, and implement recommendations in time.',
      'poshStudy3Bullet5':
          'Confidentiality applies to complainant, respondent, witnesses, and proceedings.',
      'poshStudy3Bullet6':
          'A complaint is not fake just because it could not be proven; deliberate falsehood is a different standard.',
      'poshStudy4Title': 'Important POSH Boundaries',
      'poshStudy4Bullet1':
          'Do not use the mechanism for unrelated personal disputes or knowingly fabricated allegations.',
      'poshStudy4Bullet2': 'Do not delete evidence or pressure witnesses.',
      'poshStudy4Bullet3':
          'Do not ignore repeated small incidents; patterns matter.',
      'poshStudy4Bullet4': 'Use factual, dated, and detailed reporting.',
      'poshStudy4Bullet5':
          'When in immediate danger, call emergency services first.',
      'poshStudy4Bullet6':
          'The POSH portal is for learning, documenting, and structured complaint preparation.',
      'studyFirst': 'Study first',
      'readAllSectionsBeforeQuiz1': 'Read all sections before Quiz 1',
      'threeLevels': 'Three levels',
      'twentyMcqsEachQuiz': '20 MCQs in each quiz',
      'quizCertificationTrack': 'Quiz Certification Track',
      'studyFirstThenClearQuizzesInOrder':
          'Study first, then clear the quizzes in order.',
      'level': 'Level',
      'levelPassed': 'Level Passed',
      'passed': 'Passed',
      'available': 'Available',
      'locked': 'Locked',
      'submitQuiz': 'Submit quiz',
      'next': 'Next',
      'unlocked': 'Unlocked',
      'quizNotClearedYet': 'Quiz not cleared yet',
      'reviewStudy': 'Review study',
      'retry': 'Retry',
      'viewCertificate': 'View certificate',
      'continueLabel': 'Continue',
      'poshCertified': 'POSH Certified',
      'fileWorkplaceComplaint': 'File Workplace Complaint',
      'fileWorkplaceComplaintSubtitle':
          'Prepare and submit a detailed complaint record. In immediate danger, call 112 first.',
      'keepRecordsFactual':
          'Keep your records factual and attach evidence when possible.',
      'yourFullName': 'Your Full Name',
      'yourPhoneNumber': 'Your Phone Number',
      'yourEmailAddress': 'Your Email Address',
      'accusedPersonName': 'Accused Person Name',
      'companyWorkplaceName': 'Company / Workplace Name',
      'incidentDateDdMmYyyy': 'Incident Date (DD/MM/YYYY)',
      'incidentLocation': 'Incident Location',
      'witnessesIfAny': 'Witnesses (if any)',
      'detailedIncidentDescription': 'Detailed Incident Description',
      'submitting': 'Submitting...',
      'submitComplaint': 'SUBMIT COMPLAINT',
      'guideIntro':
          'This guide is educational and operational. It explains process, boundaries, documentation, and escalation under the POSH framework in India.',
      'legalDisclaimer':
          'Legal Disclaimer: This guide is not a substitute for case-specific legal advice. For critical matters, consult a qualified lawyer, HR-POSH expert, or competent authority.',
      'guide1Title': '1. Background And Objective',
      'guide1Body':
          'The POSH Act creates a legal framework to prevent and address sexual harassment at work while protecting dignity and safe working conditions.',
      'guide2Title': '2. Where It Applies',
      'guide2Body':
          'It applies to public and private workplaces, schools, hospitals, NGOs, sports setups, domestic-work settings, and travel connected to employment.',
      'guide3Title': '3. Who Is Protected',
      'guide3Body':
          'The law primarily protects women at the workplace, including employees, trainees, interns, volunteers, contract staff, and visitors in that context.',
      'guide4Title': '4. What Counts As Sexual Harassment',
      'guide4Body':
          'Unwelcome physical contact, sexual requests, sexual remarks, pornography, and other verbal, non-verbal, or digital conduct of a sexual nature can count.',
      'guide5Title': '5. Internal Committee (IC) Requirements',
      'guide5Body':
          'Workplaces with 10 or more employees must form an Internal Committee with the required composition, including a presiding officer and an external member.',
      'guide6Title': '6. Complaint Timeline And Format',
      'guide6Body':
          'Complaints are usually filed in writing within 3 months. They should include parties, dates, location, facts, witnesses, evidence, and the relief sought.',
      'guide7Title': '7. Conciliation And Inquiry',
      'guide7Body':
          'Conciliation is voluntary. If it does not happen, the IC runs a fair inquiry where both sides are heard and the process stays written and documented.',
      'guide8Title': '8. Interim Relief During Proceedings',
      'guide8Body':
          'Interim relief can include transfer, leave, reporting-line changes, no-contact directions, work-from-home changes, or security support.',
      'guide9Title': '9. Inquiry Outcome And Employer Action',
      'guide9Body':
          'If proven, the IC can recommend action such as warning, apology, counseling, promotion impact, termination, or compensation according to service rules.',
      'guide10Title': '10. Police Complaint And Criminal Law',
      'guide10Body':
          'POSH does not replace criminal remedies. If the facts show a criminal offense, the complainant can also file a police complaint or FIR.',
      'guide11Title': '11. Confidentiality Rules',
      'guide11Body':
          'The identities of parties and witnesses, inquiry details, findings, and actions should stay confidential unless the law requires disclosure.',
      'guide12Title': '12. False Complaints: Correct Legal Position',
      'guide12Body':
          'A complaint is not automatically malicious just because it was not proven. Deliberate falsehood or forged evidence is a different standard.',
      'guide13Title': '13. How Not To Misuse The Act',
      'guide13Body':
          'Do not fabricate allegations, tamper with evidence, coach witnesses, or use the process for unrelated personal disputes.',
      'guide14Title': '14. Employer Compliance Checklist',
      'guide14Body':
          'Employers should form the IC correctly, publish the POSH policy, train staff, display the complaint channel, document inquiries, and avoid retaliation.',
      'guide15Title': '15. Practical Evidence Checklist',
      'guide15Body':
          'Preserve chats, emails, call logs, timestamps, witness names, complaint history, and relevant medical or mental-health records.',
      'guide16Title': '16. Appeals And Further Remedies',
      'guide16Body':
          'Depending on the rules and law, parties may challenge outcomes through appellate channels or seek external legal remedies.',
      'guide17Title': '17. Good-Faith Use Of POSH Portal',
      'guide17Body':
          'Use the portal to create records, file structured complaints, and prepare for IC or police processes. In danger, call emergency services first.',
      'safeRouteChanged': 'Safe route changed',
      'dailyRouteGuard': 'Daily Route Guard',
      'routeGuardDialogTitle': 'Daily route changed',
      'routeGuardDialogMessage':
          'You moved away from your usual route. Confirm you are safe.',
      'routeGuardConfirmWithin': 'Confirm within {seconds}s.',
      'routeGuardDeviationMeters':
          'About {meters} m from your usual path.',
      'routeGuardLearningRoute': 'Learning route',
      'routeGuardRoutinesLearned': '{count} routine(s) learned',
      'routeGuardIntelligenceLimited': 'Area data limited',
      'routeGuardMapRouteActive': 'Map route active',
      'safetyVerdictSafe': 'Generally safe',
      'safetyVerdictSafeSummary':
          'This area feels generally safe right now based on your live location.',
      'safetyVerdictCaution': 'Use caution',
      'safetyVerdictCautionSummary':
          'Use extra caution here—some risk signals were detected nearby.',
      'safetyVerdictHighRisk': 'Higher concern',
      'safetyVerdictHighRiskSummary':
          'This area may not feel safe right now, especially for women and elderly users.',
      'safetyVerdictMonitoring': 'Still learning',
      'safetyVerdictMonitoringSummary':
          'Live area intelligence is still building. Stay aware while we learn your surroundings.',
      'safetyWhyNotSafeTitle': 'Why this area may not feel safe',
      'safetyReasonDrugActivity':
          'Recent drug-related activity reported in this area.',
      'safetyReasonChainSnatching':
          'Chain-snatching cases have been reported nearby.',
      'safetyReasonTheftProne':
          'This stretch is known for theft-related incidents.',
      'safetyReasonHarassmentReports':
          'Harassment or assault reports have been recorded nearby.',
      'safetyReasonPoorLighting':
          'Poor street lighting may reduce visibility here.',
      'safetyReasonLowFootfall':
          'Low pedestrian activity makes this area feel isolated.',
      'safetyReasonCrimeActivity':
          'Incident activity remains elevated in the surrounding area.',
      'safetyReasonLimitedSupport':
          'Limited nearby emergency support points may slow rapid assistance.',
      'safetyReasonNightRisk':
          'Night-time conditions reduce visibility and public activity.',
      'safetyReasonGpsLimited':
          'Live location precision is limited; assessment may update as GPS improves.',
      'safetyReasonUnsafeNightlife':
          'Unsafe nightlife or red-light activity may increase risk here.',
      'safetyReasonGeneralCaution':
          'Additional caution is advised in this area.',
      'safetyReasonLimitedData':
          'Verified live area data is limited — stay extra alert here.',
      'routeVerdictChanged': 'Route changed',
      'routeVerdictChangedSummary':
          'You moved away from your usual route. Please confirm you are safe.',
      'routeVerdictLearning': 'Learning route',
      'routeVerdictLearningSummary':
          'Daily Route Guard is learning your travel patterns from live GPS.',
      'routeVerdictOnTrack': 'On usual route',
      'routeVerdictOnTrackSummary':
          'You appear to be following your learned safer daily route.',
      'routeVerdictCaution': 'Route caution',
      'routeVerdictCautionSummary':
          'Some route conditions need extra attention right now.',
      'routeVerdictAlert': 'Route alert',
      'routeVerdictAlertSummary':
          'Your current route may not match your usual safer pattern.',
      'refresh': 'Refresh',
      'openMap': 'Open map',
      'resetHomeWorkplaceRouteLearning': 'Reset home-workplace route learning',
      'homeWorkplaceRouteLearningReset': 'Home-workplace route learning reset.',
      'safetyCheckEndsIn': 'Safety check ends in',
      'unlessYouConfirm': 'unless you confirm.',
      'imSafe': 'I am safe',
      'pleaseFillAllRequiredDetails': 'Please fill all required details.',
      'complaintSubmittedSuccessfully': 'Complaint submitted successfully.',
      'submissionFailedTryAgain': 'Submission failed. Please try again.',
      'openDetailedPoshActGuide': 'OPEN DETAILED POSH ACT GUIDE',
      'clearPreviousQuizToUnlockThisLevel':
          'Clear the previous quiz to unlock this level.',
      'previous': 'Previous',
      'retryQuiz': 'Retry quiz',
      'pleaseAnswerEveryQuestionFirst': 'Please answer every question first.',
      'pleaseAnswerThisQuestionBeforeContinuing':
          'Please answer this question before continuing.',
      'currentLevel': 'Current level',
      'detailedPoshActGuide': 'Detailed POSH Act Guide',
      'cyberLawHubTitle': 'Cyber Crime Law Library',
      'cyberLawHubSubtitle': 'Know your rights. Know the law. Know how to fight back.',
      'cyberLawHelplineTitle': 'Emergency Helplines',
      'cyberLawHelplineDesc': 'Cyber Crime: 1930  |  Women: 181  |  Child: 1098  |  Police: 112',
      'cyberLawOverviewHeader': 'Overview',
      'cyberLawActsHeader': 'Applicable Laws & Sections',
      'cyberLawPunishmentHeader': 'Legal Punishment',
      'cyberLawWhatToDoHeader': 'If You Are a Victim',
      'cyberLawReportHeader': 'Where to Report',
    },
    'hi': {
      'appTitle': 'सुरक्षा',
      'greetingHello': 'नमस्ते',
      'welcomeBack': 'वापस स्वागत है',
      'signInToContinue': 'अपनी सुरक्षा यात्रा जारी रखने के लिए साइन इन करें',
      'emailOrPhone': 'ईमेल या फोन नंबर',
      'password': 'पासवर्ड',
      'login': 'लॉगिन',
      'emergencyContactsInformed': 'आपातकालीन संपर्कों को सूचित किया गया',
      'liveLocationSharedWith': 'लाइव लोकेशन साझा की गई है:',
      'fetchingLocation': 'स्थान प्राप्त किया जा रहा है...',
      'liveFeedActive': 'लाइव फ़ीड सक्रिय ({time})',
      'startingLiveTransmission': 'लाइव ट्रांसमिशन शुरू हो रहा है...',
      'liveTransmissionPaused': 'लाइव ट्रांसमिशन रुका हुआ है',
      'emergencyModeActive': 'आपातकालीन मोड सक्रिय',
      'helpOnTheWay': 'मदद आ रही है। आपकी लाइव लोकेशन साझा की जा रही है।',
      'currentLocation': 'मौजूदा स्थान',
      'status': 'स्थिति',
      'iAmSafeCancelSos': 'मैं सुरक्षित हूँ - SOS रद्द करें',
      'myProfile': 'मेरा प्रोफाइल',
      'profileSubtitle':
          'अपनी सुरक्षा पहचान, भाषा और आपातकालीन तैयारी संभालें।',
      'profileOverview': 'प्रोफाइल सारांश',
      'profileStatsTitle': 'आपकी सुरक्षा झलक',
      'profileHeroCta': 'तेज़ सहायता के लिए प्रोफाइल को निजी बनाएं।',
      'languageSelectionTitle': 'ऐप भाषा चुनें',
      'darkMode': 'डार्क मोड',
      'darkModeSubtitleOn': 'डार्क ब्लू थीम',
      'darkModeSubtitleOff': 'हल्की शांत थीम',
      'language': 'भाषा',
      'contentLanguage': 'ऐप की सामग्री की भाषा',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'editProfile': 'प्रोफाइल संपादित करें',
      'editPhoneNumber': 'फोन नंबर संपादित करें',
      'addEmergencyContactTitle': 'आपातकालीन संपर्क जोड़ें',
      'editEmergencyContactTitle': 'आपातकालीन संपर्क संपादित करें',
      'editProfileDetails': 'प्रोफाइल विवरण संपादित करें',
      'editMedicalProfile': 'मेडिकल प्रोफाइल संपादित करें',
      'fullName': 'पूरा नाम',
      'email': 'ईमेल',
      'phone': 'फोन नंबर',
      'relation': 'नाते',
      'loadingNearbySafetyPoints': 'नज़दीकी सुरक्षा बिंदु लोड हो रहे हैं...',
      'unableToFetchLocation':
          'स्थान प्राप्त नहीं किया जा सका। खुले आसमान के पास जाएँ और फिर प्रयास करें।',
      'couldNotFetchYourLocation': 'आपका स्थान प्राप्त नहीं किया जा सका।',
      'youAreHere': 'आप यहाँ हैं',
      'surakshaLiveLocationNotificationTitle': 'सुरक्षा लाइव लोकेशन',
      'surakshaLiveLocationNotificationText':
          'सुरक्षा सुविधाओं के लिए लाइव लोकेशन ट्रैक की जा रही है।',
      'journeyStopped': 'यात्रा बंद की गई',
      'totalRoute': 'कुल मार्ग',
      'stop': 'बंद करें',
      'start': 'शुरू करें',
      'name': 'नाम',
      'bloodGroup': 'ब्लड ग्रुप',
      'allergies': 'एलर्जी',
      'medicalConditions': 'चिकित्सीय स्थितियां',
      'currentMedications': 'वर्तमान दवाएं',
      'phoneNumber': 'फोन नंबर',
      'notProvided': 'उपलब्ध नहीं',
      'emergencyContacts': 'आपातकालीन संपर्क',
      'contactsSaved': 'संपर्क सहेजे गए',
      'emergencyContactList': 'आपातकालीन संपर्क सूची',
      'addEmergencyContact': 'आपातकालीन संपर्क जोड़ें',
      'addNewContact': 'नया संपर्क जोड़ें',
      'logoutSession': 'लॉगआउट',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'ok': 'ठीक है',
      'saving': 'सहेजा जा रहा है...',
      'saved': 'सहेजा गया',
      'screamDetection': 'चीख पहचान',
      'screamDetectionEnabled': 'चीख पहचान चालू की गई।',
      'screamDetectionDisabled': 'चीख पहचान बंद की गई।',
      'screamDetectionEnableFailed': 'चीख पहचान चालू नहीं की जा सकी।',
      'distressSensitivity': 'पहचान संवेदनशीलता',
      'distressSensitivitySubtitle':
          'उच्च = धीमी चीख भी; निम्न = कम गलत अलर्ट।',
      'distressSensitivity_low': 'निम्न',
      'distressSensitivity_medium': 'मध्यम',
      'distressSensitivity_high': 'उच्च',
      'distressTestMode': 'टेस्ट मोड (कोई SOS नहीं)',
      'distressTestModeSubtitle':
          'चीख/शब्द पहचानें लेकिन SOS न भेजें। सटीकता जाँच के लिए।',
      'distressLastHeard': 'अंतिम सुना',
      'microphoneSafetyMonitorActive': 'माइक्रोफोन सुरक्षा मॉनिटर चालू है।',
      'microphoneSafetyMonitorInactive':
          'यह बंद रहने पर माइक्रोफोन बंद रहता है।',
      'impactDetection': 'झटका पहचान',
      'impactDetectionEnabled': 'झटका पहचान चालू की गई।',
      'impactDetectionDisabled': 'झटका पहचान बंद की गई।',
      'impactDetectionEnableFailed': 'झटका पहचान चालू नहीं की जा सकी।',
      'motionSensorsActive': 'मोशन सेंसर अचानक झटके पर नज़र रख रहे हैं।',
      'motionSensorsInactive': 'यह बंद रहने पर मोशन सेंसर बंद रहते हैं।',
      'phoneNumberRequired': 'फोन नंबर आवश्यक है।',
      'nameAndPhoneRequired': 'नाम और फोन नंबर आवश्यक हैं।',
      'duplicatePhoneNumber': 'यह फोन नंबर पहले से सहेजा गया है।',
      'savedLocallyRetryLater':
          'स्थानीय रूप से सहेजा गया। सर्वर सिंक बाद में फिर से कोशिश करेगा।',
      'photoSavedLocally': 'फ़ोटो स्थानीय रूप से सहेजी गई।',
      'serverSyncWillRetryLater': 'सर्वर सिंक बाद में फिर से कोशिश करेगा।',
      'profileSavedTitle': 'प्रोफाइल सहेजा गया',
      'profileSavedMessage': 'आपकी जानकारी सुरक्षित रूप से सहेज ली गई है।',
      'medicalSavedTitle': 'मेडिकल प्रोफाइल सहेजा गया',
      'medicalSavedMessage': 'आपकी मेडिकल जानकारी सफलतापूर्वक अपडेट हो गई है।',
      'contactSavedTitle': 'संपर्क सहेजा गया',
      'contactSavedMessage': 'आपातकालीन संपर्क विवरण सफलतापूर्वक अपडेट हो गए।',
      'draftSavedTitle': 'ड्राफ्ट सहेजा गया',
      'draftSavedMessage': 'आपका ड्राफ्ट इस डिवाइस पर सुरक्षित कर लिया गया है।',
      'emergencyServices': 'आपातकालीन सेवाएं',
      'communityAlerts': 'समुदाय अलर्ट',
      'safetyRegionLabel': 'क्षेत्र',
      'safetyDataDisclaimerTitle': 'डेटा स्रोत',
      'safetyConfidenceSuffix': 'विश्वास',
      'safetySourceOpenStreetMap': 'OpenStreetMap',
      'safetySourceSunset': 'सूर्यास्त API',
      'safetySourceCrowd': 'अज्ञात भीड़',
      'safetySourceSurakshaReports': 'Suraksha रिपोर्ट',
      'safetySourceSurakshaEngine': 'Suraksha इंजन',
      'safetySourceSurakshaCommunity': 'समुदाय सत्यापित',
      'safetySourceRegionalGuidance': 'क्षेत्रीय मार्गदर्शन',
      'safetyDimCrime': 'अपराध',
      'safetyDimInfrastructure': 'रोशनी',
      'safetyDimSupport': 'सहायता',
      'safetyDimVisibility': 'दृश्यता',
      'safetyDimTemporal': 'समय',
      'safetySourceGridModel': 'ग्रिड मॉडल',
      'safetySourceOpenDataDistrict': 'जिला ओपन डेटा',
      'safetyUpdatedAgo': 'अपडेट',
      'aiSummaryFromGemini': 'AI सारांश (Gemini)',
      'aiSummaryFromTemplate': 'AI सारांश (ऑफ़लाइन)',
      'journeySafetyAlerts': 'यात्रा सुरक्षा अलर्ट',
      'journeySafetyAlertsSubtitle':
          'नेविगेशन के दौरान उच्च जोखिम वाले क्षेत्र में प्रवेश पर पुश और इन-ऐप अलर्ट।',
      'journeyRerouteHint': 'अधिक सुरक्षित मार्ग उपलब्ध',
      'tapForAlerts': 'अलर्ट देखने के लिए टैप करें',
      'tapRefreshTryAgain': 'फिर कोशिश के लिए रिफ्रेश टैप करें',
      'loadingLiveAreaAlerts': 'लाइव क्षेत्र अलर्ट लोड हो रहे हैं...',
      'checkingTrafficTransportNearbyActivity':
          'ट्रैफ़िक, परिवहन और आसपास की गतिविधि जाँच रहे हैं',
      'liveAlertsWillAppearHere': 'लाइव अलर्ट यहाँ दिखेंगे',
      'keepGpsOnForRealtimeCommunityUpdates':
          'रीयलटाइम community updates के लिए GPS चालू रखें',
      'locationRequiredTitle': 'स्थान आवश्यक है',
      'locationRequiredMessage':
          'Suraksha को काम करने के लिए GPS और स्थान अनुमति चाहिए। जारी रखने के लिए इन्हें सक्षम करें।',
      'locationAutoRefreshMessage':
          'स्थान सक्षम होने के बाद सेवाएँ स्वतः ताज़ा होंगी।',
      'retryLocation': 'स्थान सेटअप पुनः प्रयास करें',
      'womenHelpline': 'महिला हेल्पलाइन',
      'nearbyServices': 'नज़दीकी सेवाएं',
      'nearbyHospitals': 'नज़दीकी अस्पताल',
      'policeStations': 'पुलिस स्टेशन',
      'nearbyWashrooms': 'नज़दीकी वॉशरूम',
      'nearbyBloodBanks': 'नज़दीकी ब्लड बैंक',
      'nearbyPharmacies': 'नज़दीकी फ़ार्मेसी',
      'tapToLoadNearby': 'नज़दीकी सेवाएं लोड करने के लिए बटन दबाएं।',
      'noNearbyPlaces': '5 किमी के दायरे में कोई स्थान नहीं मिला।',
      'safeZoneActive': 'सुरक्षा प्राथमिकता',
      'helloKaveri': 'नमस्ते, कावेरी',
      'openSafetyMap': 'सुरक्षा मानचित्र खोलें',
      'openSafetyMapConfirm': 'क्या आप यह स्थान मानचित्र पर देखना चाहते हैं?',
      'mapOpenChoiceTitle': 'स्थान खोलें',
      'mapOpenChoiceMessage': 'आप इस स्थान को कैसे खोलना चाहते हैं, चुनें।',
      'mapOpenChoiceSuraksha': 'सुरक्षा मानचित्र',
      'mapOpenChoiceGoogle': 'गूगल मैप्स',
      'yes': 'हाँ',
      'no': 'नहीं',
      'couldNotOpenDialer': 'डायलर नहीं खुल सका',
      'policeEmergency': 'पुलिस आपातकालीन',
      'scanningNearbyPlaces': 'नज़दीकी स्थान स्कैन किए जा रहे हैं...',
      'nearbyResultsCount': '{count} नज़दीकी परिणाम',
      'chooseServiceToScanYourArea':
          'अपने वर्तमान क्षेत्र को स्कैन करने के लिए नीचे एक सेवा चुनें।',
      'cyberCrimeProtection': 'साइबर क्राइम सुरक्षा',
      'aiAssist': 'एआई सहायता',
      'report': 'रिपोर्ट',
      'vault': 'वॉल्ट',
      'learn': 'सीखें',
      'deepfake': 'डीपफेक',
      'aiScamFraudAssistantTitle': 'एआई घोटाला और धोखाधड़ी पहचान असिस्टेंट',
      'pasteEvidenceContext':
          'संदिग्ध संदेश, लिंक, चैट या प्रश्न पेस्ट करें। साक्ष्य संदर्भ के रूप में स्क्रीनशॉट संलग्न करें।',
      'suspiciousMessageLabel': 'संदिग्ध संदेश, ईमेल या चैट',
      'pasteFullMessageHereHint': 'पूरा संदेश यहाँ पेस्ट करें...',
      'suspiciousLinksLabel': 'संदिग्ध लिंक',
      'urlHint': 'https://example.com, bit.ly/...',
      'askQuestionLabel': 'एक प्रश्न पूछें',
      'scamQuestionHint': 'क्या यह घोटाला है? क्या यह प्रोफ़ाइल नकली है?',
      'attachScreenshot': 'स्क्रीनशॉट संलग्न करें',
      'analyze': 'विश्लेषण करें',
      'selectIncidentType': 'घटना प्रकार चुनें',
      'attachScreenshotsOrProof': 'स्क्रीनशॉट या लेनदेन प्रमाण संलग्न करें',
      'incidentDescription': 'घटना का विवरण',
      'incidentDetailsHint':
          'क्या हुआ इसका विवरण दें, उपयोगकर्ता नाम, राशि, धमकियाँ और प्लेटफ़ॉर्म।',
      'suspectContactLabel': 'फोन/ईमेल/प्रोफ़ाइल लिंक',
      'suspectContactHint': 'संदिग्ध संपर्क या प्रोफ़ाइल URL',
      'transactionIdLabel': 'लेन-देन आईडी',
      'transactionIdHint': 'यदि वित्तीय धोखाधड़ी हो तो UPI/ref नंबर',
      'incidentTime': 'घटना समय: {time}',
      'pdfReady': 'PDF तैयार',
      'newReport': 'नई रिपोर्ट',
      'saveDraft': 'ड्राफ्ट सहेजें',
      'reportGenerated': 'रिपोर्ट तैयार हुई।',
      'draftSavedOnline': 'ड्राफ्ट ऑनलाइन सहेजा गया।',
      'couldNotSubmitOnline':
          'ऑनलाइन सबमिट नहीं हो सका। कृपया फिर प्रयास करें।',
      'secureEvidenceVault': 'सुरक्षित साक्ष्य वॉल्ट',
      'uploadTagSearchPackageEvidence':
          'साइबर साक्ष्य अपलोड करें, टैग करें, खोजें और पैकेज करें। बैकएंड फ़ाइलें AES एन्क्रिप्टेड हैं।',
      'takeQuiz': 'क्विज़ लें',
      'progressBadge': '{percent}% पूरा | बैज: {badge}',
      'cyberDefender': 'साइबर डिफेंडर',
      'cyberLearner': 'साइबर लर्नर',
      'deepfakeSubtitle':
          'जागरूकता, आपातकालीन प्रतिक्रिया, कानूनी मार्गदर्शन और हेल्पलाइन पहुंच।',
      'deepfakeWarning':
          'यदि कोई मोर्फ़्ड/निजी मीडिया लीक करने की धमकी देता है, तो भुगतान न करें या समझौता न करें। साक्ष्य सुरक्षित रखें और तुरंत रिपोर्ट करें।',
      'emergencyActions': 'आपातकालीन कार्यवाही',
      'call1930': '1930 पर कॉल करें',
      'police100': 'पुलिस 100',
      'cyberPortal': 'साइबर पोर्टल',
      'uploadEncryptedEvidence': 'एन्क्रिप्टेड साक्ष्य अपलोड करें',
      'noFilesSelectedYet': 'कोई फ़ाइलें अभी तक चयनित नहीं हुई हैं।',
      'generate': 'जनरेट करें',
      'generatedComplaint': 'उत्पन्न शिकायत',
      'reportSummaryUnavailable': 'रिपोर्ट सारांश उपलब्ध नहीं है।',
      'pdfPayloadGenerated':
          'PDF पेलोड तैयार हुआ। निर्यात एकीकरण बैकएंड उत्तर से सहेज/साझा कर सकता है।',
      'evidenceTitleLabel': 'साक्ष्य शीर्षक',
      'evidenceTitleHint': 'धमकी स्क्रीनशॉट, UPI प्रमाण...',
      'category': 'श्रेणी',
      'private': 'निजी',
      'tags': 'टैग',
      'tagsHint': 'ब्लैकमेल, इंस्टाग्राम, पेमेंट',
      'finish': 'समाप्त',
      'searchVault': 'वॉल्ट खोजें',
      'searchByTitle': 'शीर्षक द्वारा खोजें',
      'noEvidenceFound':
          'कोई साक्ष्य नहीं मिला। अपना सुरक्षित वॉल्ट शुरू करने के लिए साक्ष्य अपलोड करें।',
      'sessionExpiredSignIn': 'सत्र समाप्त। कृपया फिर साइन इन करें।',
      'loginRequiredCyber': 'सुरक्षित साइबर सुविधाओं के लिए फिर लॉगिन करें।',
      'fileTooLarge10Mb': 'फ़ाइल बहुत बड़ी है। अधिकतम 10 MB।',
      'networkServerIssue': 'नेटवर्क या सर्वर समस्या। फिर प्रयास करें।',
      'couldNotSharePdf': 'PDF साझा नहीं हो सका।',
      'couldNotExportEvidence': 'साक्ष्य पैकेज निर्यात नहीं हो सका।',
      'riskLevel': 'जोखिम स्तर',
      'recommendedActions': 'अनुशंसित कार्य',
      'safetyTips': 'सुरक्षा सुझाव',
      'encrypted': 'एन्क्रिप्टेड',
      'notEncrypted': 'एन्क्रिप्टेड नहीं',
      'linkedToReport': 'रिपोर्ट से जुड़ा',
      'preview': 'पूर्वावलोकन',
      'download': 'डाउनलोड',
      'delete': 'हटाएं',
      'noUnlinkedEvidence': 'वॉल्ट में कोई अनलिंक्ड साक्ष्य नहीं।',
      'minDescriptionChars': 'कम से कम 10 अक्षर का विवरण जोड़ें।',
      'draftPendingDetails': 'ड्राफ्ट रिपोर्ट विवरण लंबित।',
      'evidenceFilesSecured': '{count} साक्ष्य फ़ाइल(एं) वॉल्ट में सुरक्षित।',
      'vaultEvidenceLinked': '{count} वॉल्ट आइटम रिपोर्ट से जुड़े।',
      'summaryStep': 'सारांश',
      'myReports': 'मेरी रिपोर्ट',
      'noSubmittedReportsYet': 'अभी कोई रिपोर्ट नहीं। शिकायत बनाएं।',
      'draft': 'ड्राफ्ट',
      'pickFromGallery': 'गैलरी',
      'pickFile': 'फ़ाइल चुनें',
      'attachFromVault': 'वॉल्ट से',
      'vaultItemsSelected': '{count} वॉल्ट आइटम चयनित',
      'uploadingEvidence': 'साक्ष्य अपलोड हो रहा है...',
      'selectVaultEvidence': 'वॉल्ट साक्ष्य चुनें',
      'analyzeInputRequired': 'संदेश, लिंक, प्रश्न पेस्ट करें या स्क्रीनशॉट संलग्न करें।',
      'clearScreenshot': 'स्क्रीनशॉट हटाएं',
      'screenshotTextExtracted': 'स्क्रीनशॉट से निकाला गया पाठ',
      'evidenceEncryptedSaved': 'साक्ष्य एन्क्रिप्ट करके सहेजा गया।',
      'uploadFailed': 'अपलोड विफल।',
      'previewFailed': 'पूर्वावलोकन विफल।',
      'downloadFailed': 'डाउनलोड विफल।',
      'deleteEvidenceTitle': 'साक्ष्य हटाएं?',
      'deleteEvidenceConfirm': '"{title}" को वॉल्ट से हटाएं?',
      'evidenceDeleted': 'साक्ष्य हटाया गया।',
      'deleteFailed': 'हटाना विफल।',
      'exportFailed': 'निर्यात विफल।',
      'exportEvidencePackage': 'साक्ष्य पैकेज निर्यात',
      'filterAll': 'सभी',
      'filterLinked': 'जुड़े हुए',
      'filterUnlinked': 'अनलिंक्ड',
      'reportDetails': 'रिपोर्ट विवरण',
      'linkedEvidence': 'जुड़ा साक्ष्य',
      'noLinkedEvidence': 'इस रिपोर्ट से कोई साक्ष्य नहीं जुड़ा।',
      'digitalSafetyLearningHub': 'डिजिटल सुरक्षा शिक्षा केंद्र',
      'learningHubSubtitle': 'फ़िशिंग, UPI, गोपनीयता और डीपफेक कौशल बनाएं।',
      'cyberSafetyScore': 'साइबर सुरक्षा स्कोर',
      'cyberSafetyScoreUpdated': 'साइबर सुरक्षा स्कोर: {score}',
      'catFinancialFraud': 'वित्तीय धोखाधड़ी',
      'catCyberStalking': 'साइबर स्टॉकिंग',
      'catOnlineBullying': 'ऑनलाइन बुलिंग',
      'catIdentityTheft': 'पहचान की चोरी',
      'catSocialMediaHarassment': 'सोशल मीडिया उत्पीड़न',
      'catHarassment': 'उत्पीड़न',
      'catBlackmail': 'ब्लैकमेल',
      'catFakeProfile': 'नकली प्रोफ़ाइल',
      'catDeepfakeThreat': 'डीपफेक धमकी',
      'catDeepfakeScam': 'डीपफेक घोटाला',
      'catFakeJobScam': 'नकली नौकरी घोटाला',
      'catUpiFraud': 'UPI धोखाधड़ी',
      'catOther': 'अन्य',
      'evidenceCatAll': 'सभी',
      'evidenceCatScreenshot': 'स्क्रीनशॉट',
      'evidenceCatAudio': 'ऑडियो',
      'evidenceCatThreatMessage': 'धमकी संदेश',
      'evidenceCatImage': 'छवि',
      'evidenceCatTransactionProof': 'लेनदेन प्रमाण',
      'evidenceCatDocument': 'दस्तावेज़',
      'evidenceCatOther': 'अन्य',
      'multiSelectNone': 'कोई चयन नहीं',
      'multiSelectCount': '{count} चयनित',
      'filterCategories': 'श्रेणी फ़िल्टर',
      'filterLinkStatus': 'लिंक स्थिति',
      'additionalCategoriesNote': 'अतिरिक्त घटना प्रकार',
      'configureServer': 'सर्वर कॉन्फ़िगर करें',
      'configureServerHint':
          'PC IP दर्ज करें जहाँ बैकएंड चल रहा है। उदाहरण: http://192.168.1.5:5000/api',
      'serverUrlHint': 'http://192.168.1.5:5000/api',
      'serverUrlSaved': 'सर्वर URL सहेजा गया। कनेक्शन पुनः प्रयास...',
      'cannotReachServer':
          'सर्वर से कनेक्ट नहीं हो पा रहा। कृपया अपना इंटरनेट कनेक्शन जाँचें और पुनः प्रयास करें।',
      'fixConnection': 'पुनः प्रयास करें',
      'deepfakeEmergencySupportTitle':
          'डीपफेक और मॉर्फ़्ड इमेज इमरजेंसी सहायता',
      'medicalHealthVault': 'मेडिकल हेल्थ वॉल्ट',
      'keepEmergencyMedicalInformationOrganized':
          'आपातकालीन चिकित्सा जानकारी को तेज़ उपयोग के लिए व्यवस्थित रखें।',
      'emergencyMedicalId': 'आपातकालीन मेडिकल आईडी',
      'scanInCaseOfMedicalEmergency':
          'चिकित्सीय आपातकाल के मामले में स्कैन करें',
      'medicalProfileSaved': 'मेडिकल प्रोफ़ाइल सहेजी गई',
      'medicalDetailsReady':
          'आपकी मेडिकल जानकारी आपातकालीन उपयोग के लिए तैयार है।',
      'savedLocallyOnThisDevice': 'यह डिवाइस पर स्थानीय रूप से सहेजा गया।',
      'medicalProfileSavedLocallySyncRetryLater':
          'चिकित्सीय प्रोफ़ाइल स्थानीय रूप से सहेजी गई। सिंक बाद में पुन: प्रयास करेगा।',
      'certificateDetails': 'प्रमाणपत्र विवरण',
      'issuedOn': '{date} को जारी किया गया',
      'poshCertifiedMessage':
          'आपने तीनों क्विज़ स्तर पूरे किए हैं और मजबूत POSH एक्ट ज्ञान दिखाया है।',
      'validForPoshCertificate':
          'मान्य: POSH एक्ट जागरूकता और कार्यस्थल सुरक्षा सीखने के लिए',
      'safeZoneUpdatedNearby': 'नज़दीक सुरक्षित क्षेत्र अपडेट हुआ',
      'crowdedAreaWarning': 'भीड़भाड़ क्षेत्र चेतावनी',
      'minsAgo2': '2 मिनट पहले',
      'minsAgo15': '15 मिनट पहले',
      'map': 'मैप',
      'medical': 'मेडिकल',
      'cyber': 'साइबर',
      'poshPortal': 'पॉश पोर्टल',
      'study': 'अध्ययन',
      'quizzes': 'क्विज़',
      'complaint': 'शिकायत',
      'poshActLearningHub': 'POSH अधिनियम अध्ययन केंद्र',
      'poshStudy1Title': 'POSH अधिनियम क्या कवर करता है',
      'poshStudy1Bullet1':
          'POSH अधिनियम कार्यस्थल पर महिलाओं के यौन उत्पीड़न (2013) को संबोधित करता है।',
      'poshStudy1Bullet2':
          'यह गरिमा, समानता और सुरक्षित कार्य स्थितियों की रक्षा करता है।',
      'poshStudy1Bullet3':
          'यह सार्वजनिक व निजी कार्यस्थलों, कार्यालयों, दुकानों, अस्पतालों, स्कूलों, NGO और नियोक्ता द्वारा प्रदान किए गए परिवहन पर लागू होता है।',
      'poshStudy1Bullet4':
          'कानून कर्मचारियों, प्रशिक्षुओं, इंटर्न, संविदा कर्मचारियों, स्वयंसेवकों और कार्यस्थल पर आने वाले आगंतुकों को कवर करता है।',
      'poshStudy1Bullet5':
          'यौन प्रकृति का अवांछित आचरण मौखिक, लिखित, डिजिटल या शारीरिक हो सकता है।',
      'poshStudy1Bullet6':
          'उदाहरण: अवांछित छूना, यौन टिप्पणियाँ, संदेश, दोहराया उत्पीड़न, या अश्लील सामग्री दिखाना।',
      'poshStudy2Title': 'शिकायत प्रक्रिया और आंतरिक समिति (IC)',
      'poshStudy2Bullet1':
          'शिकायत सामान्यतः घटना के 3 महीनों के भीतर लिखित रूप में दी जानी चाहिए।',
      'poshStudy2Bullet2':
          '10 या अधिक कर्मचारियों वाले कार्यस्थलों में आंतरिक समिति सही ढंग से गठित होनी चाहिए।',
      'poshStudy2Bullet3':
          'समिति में आमतौर पर एक वरिष्ठ महिला अध्यक्ष, कर्मचारी सदस्य और एक बाहरी सदस्य शामिल होते हैं।',
      'poshStudy2Bullet4':
          'सुलह केवल तब किया जा सकता है जब शिकायतकर्ता चाहे; यह जबरदस्ती नहीं होना चाहिए।',
      'poshStudy2Bullet5':
          'यदि सुलह नहीं होती, तो IC निष्पक्ष जाँच करती है जहाँ दोनों पक्षों को सुना जाता है।',
      'poshStudy2Bullet6': 'प्रक्रिया गोपनीय, लिखित और दस्तावेजीकृत रहे।',
      'poshStudy3Title': 'साक्ष्य, सुरक्षा और नियोक्ता कर्तव्य',
      'poshStudy3Bullet1':
          'चैट्स, ईमेल, स्क्रीनशॉट, कॉल लॉग, गवाहों के नाम, तिथियाँ और स्थान का रिकॉर्ड रखें।',
      'poshStudy3Bullet2':
          'अंतरिम सहायता के रूप में तबादला, रजा, संपर्क-निषेध, या रिपोर्टिंग-लाइन में बदलाव शामिल हो सकते हैं।',
      'poshStudy3Bullet3':
          'यदि तथ्य अपराध को दर्शाते हैं तो पुलिस में शिकायत/FIR भी दर्ज की जा सकती है।',
      'poshStudy3Bullet4':
          'नियोक्ता नीति दिखाएँ, कर्मचारियों को प्रशिक्षित करें, IC का समर्थन करें और सिफारिशें लागू करें।',
      'poshStudy3Bullet5':
          'गोपनीयता शिकायतकर्ता, प्रतिवादी, गवाह और कार्यवाही पर लागू होती है।',
      'poshStudy3Bullet6':
          'एक शिकायत केवल इसलिए झूठी नहीं होती कि उसे प्रमाणित नहीं किया जा सका; जानबूझकर झूठ अलग मामला है।',
      'poshStudy4Title': 'महत्वपूर्ण POSH सीमाएँ',
      'poshStudy4Bullet1':
          'अप्रासंगिक व्यक्तिगत विवादों या जानबूझकर बनाए गए आरोपों के लिए तंत्र का उपयोग न करें।',
      'poshStudy4Bullet2': 'साक्ष्य न मिटाएँ और गवाहों पर दबाव न डालें।',
      'poshStudy4Bullet3':
          'छोटी बारंबार घटनाओं की अनदेखी न करें; पैटर्न मायने रखता है।',
      'poshStudy4Bullet4':
          'तथ्यात्मक, दिनांकित और विस्तृत रिपोर्टिंग का उपयोग करें।',
      'poshStudy4Bullet5':
          'तत्काल खतरे में होने पर पहले आपातकालीन सेवाओं को कॉल करें।',
      'poshStudy4Bullet6':
          'POSH पोर्टल सीखने, दस्तावेजीकरण और संरचित शिकायत तैयारी के लिए है।',
      'studyFirst': 'पहले अध्ययन करें',
      'readAllSectionsBeforeQuiz1': 'क्विज़ 1 से पहले सभी अनुभाग पढ़ें',
      'threeLevels': 'तीन स्तर',
      'twentyMcqsEachQuiz': 'हर क्विज़ में 20 MCQ',
      'quizCertificationTrack': 'क्विज़ प्रमाणन ट्रैक',
      'studyFirstThenClearQuizzesInOrder':
          'पहले अध्ययन करें, फिर क्विज़ को क्रम से पूरा करें।',
      'level': 'स्तर',
      'levelPassed': 'स्तर पास',
      'passed': 'पास',
      'available': 'उपलब्ध',
      'locked': 'लॉक्ड',
      'submitQuiz': 'क्विज़ सबमिट करें',
      'next': 'अगला',
      'unlocked': 'अनलॉक्ड',
      'quizNotClearedYet': 'क्विज़ अभी साफ़ नहीं हुआ है',
      'reviewStudy': 'अध्ययन देखें',
      'retry': 'फिर से प्रयास करें',
      'viewCertificate': 'प्रमाणपत्र देखें',
      'continueLabel': 'जारी रखें',
      'poshCertified': 'POSH प्रमाणित',
      'fileWorkplaceComplaint': 'कार्यस्थल शिकायत दर्ज करें',
      'fileWorkplaceComplaintSubtitle':
          'विस्तृत शिकायत रिकॉर्ड तैयार करें और भेजें। तुरंत खतरे में 112 पर कॉल करें।',
      'keepRecordsFactual':
          'अपने रिकॉर्ड तथ्यात्मक रखें और संभव हो तो साक्ष्य जोड़ें।',
      'yourFullName': 'आपका पूरा नाम',
      'yourPhoneNumber': 'आपका फोन नंबर',
      'yourEmailAddress': 'आपका ईमेल पता',
      'accusedPersonName': 'आरोपी व्यक्ति का नाम',
      'companyWorkplaceName': 'कंपनी / कार्यस्थल का नाम',
      'incidentDateDdMmYyyy': 'घटना की तारीख (DD/MM/YYYY)',
      'incidentLocation': 'घटना का स्थान',
      'witnessesIfAny': 'गवाह (यदि कोई हों)',
      'detailedIncidentDescription': 'घटना का विस्तृत विवरण',
      'submitting': 'सबमिट किया जा रहा है...',
      'submitComplaint': 'शिकायत सबमिट करें',
      'guideIntro':
          'यह मार्गदर्शिका शिक्षण और संचालन के लिए है। यह भारत में POSH ढांचे के तहत प्रक्रिया, सीमाएं, दस्तावेजीकरण और आगे की कार्रवाई समझाती है।',
      'legalDisclaimer':
          'कानूनी अस्वीकरण: यह मार्गदर्शिका मामले-विशेष कानूनी सलाह का विकल्प नहीं है। महत्वपूर्ण मामलों में योग्य वकील, HR-POSH विशेषज्ञ या सक्षम प्राधिकारी से सलाह लें।',
      'guide1Title': '1. पृष्ठभूमि और उद्देश्य',
      'guide1Body':
          'POSH अधिनियम काम पर यौन उत्पीड़न को रोकने और संबोधित करने के लिए कानूनी ढांचा बनाता है और गरिमा व सुरक्षित कार्य स्थितियों की रक्षा करता है।',
      'guide2Title': '2. यह कहाँ लागू होता है',
      'guide2Body':
          'यह सार्वजनिक और निजी कार्यस्थलों, स्कूलों, अस्पतालों, NGO, खेल सेटअप, घरेलू काम और रोजगार से जुड़े सफर पर लागू होता है।',
      'guide3Title': '3. कौन संरक्षित है',
      'guide3Body':
          'यह कानून मुख्य रूप से कार्यस्थल पर महिलाओं की रक्षा करता है, जिसमें कर्मचारी, प्रशिक्षु, इंटर्न, स्वयंसेवक, संविदा कर्मचारी और उस संदर्भ में आने वाले आगंतुक शामिल हैं।',
      'guide4Title': '4. यौन उत्पीड़न क्या है',
      'guide4Body':
          'अवांछित शारीरिक संपर्क, यौन अनुरोध, यौन टिप्पणियाँ, अश्लील सामग्री, और यौन प्रकृति का अन्य मौखिक, गैर-मौखिक या डिजिटल आचरण इसमें आ सकते हैं।',
      'guide5Title': '5. आंतरिक समिति (IC) आवश्यकताएँ',
      'guide5Body':
          '10 या अधिक कर्मचारियों वाले कार्यस्थलों में आवश्यक संरचना के साथ Internal Committee बननी चाहिए, जिसमें Presiding Officer और बाहरी सदस्य शामिल हों।',
      'guide6Title': '6. शिकायत समयसीमा और प्रारूप',
      'guide6Body':
          'शिकायत आमतौर पर 3 महीने के भीतर लिखित रूप में दी जाती है। इसमें पक्ष, तिथियाँ, स्थान, तथ्य, गवाह, साक्ष्य और मांगी गई राहत शामिल होनी चाहिए।',
      'guide7Title': '7. सुलह और जाँच',
      'guide7Body':
          'सुलह स्वैच्छिक है। यदि ऐसा न हो, तो IC निष्पक्ष जाँच करती है जहाँ दोनों पक्ष सुने जाते हैं और प्रक्रिया लिखित व दस्तावेजित रहती है।',
      'guide8Title': '8. प्रक्रिया के दौरान अंतरिम राहत',
      'guide8Body':
          'अंतरिम राहत में स्थानांतरण, अवकाश, रिपोर्टिंग लाइन परिवर्तन, संपर्क-निषेध निर्देश, WFH बदलाव या सुरक्षा सहायता शामिल हो सकती है।',
      'guide9Title': '9. जाँच परिणाम और नियोक्ता की कार्रवाई',
      'guide9Body':
          'यदि आरोप सिद्ध हों, तो IC नियमों के अनुसार चेतावनी, माफी, परामर्श, प्रमोशन/वेतन वृद्धि पर प्रभाव, बर्खास्तगी या मुआवज़ा सुझा सकती है।',
      'guide10Title': '10. पुलिस शिकायत और आपराधिक कानून',
      'guide10Body':
          'POSH आपराधिक उपायों की जगह नहीं लेता। यदि तथ्य अपराध दिखाते हैं, तो शिकायतकर्ता पुलिस शिकायत या FIR भी दर्ज कर सकता है।',
      'guide11Title': '11. गोपनीयता नियम',
      'guide11Body':
          'पक्षों और गवाहों की पहचान, जाँच विवरण, निष्कर्ष और कार्रवाई गोपनीय रखी जानी चाहिए, जब तक कानून अलग से न कहे।',
      'guide12Title': '12. झूठी शिकायत: सही कानूनी स्थिति',
      'guide12Body':
          'केवल साबित न होने से शिकायत अपने आप दुर्भावनापूर्ण नहीं हो जाती। जानबूझकर झूठ या जाली साक्ष्य अलग मानक है।',
      'guide13Title': '13. अधिनियम का दुरुपयोग कैसे न करें',
      'guide13Body':
          'जानबूझकर झूठे आरोप, साक्ष्य में छेड़छाड़, गवाहों को प्रभावित करना या निजी विवादों के लिए प्रक्रिया का उपयोग न करें।',
      'guide14Title': '14. नियोक्ता अनुपालन सूची',
      'guide14Body':
          'IC सही ढंग से बनाएं, POSH नीति प्रकाशित करें, स्टाफ को प्रशिक्षित करें, शिकायत चैनल दिखाएं, जाँच दस्तावेज़ रखें और प्रतिशोध से बचें।',
      'guide15Title': '15. व्यावहारिक साक्ष्य सूची',
      'guide15Body':
          'चैट, ईमेल, कॉल लॉग, टाइमस्टैम्प, गवाहों के नाम, शिकायत इतिहास और संबंधित मेडिकल/मेंटल हेल्थ रिकॉर्ड सुरक्षित रखें।',
      'guide16Title': '16. अपील और अन्य उपाय',
      'guide16Body':
          'नियमों और कानून के अनुसार, पक्ष अपीलीय मार्गों से परिणामों को चुनौती दे सकते हैं या बाहरी कानूनी उपाय खोज सकते हैं।',
      'guide17Title': '17. POSH पोर्टल का सद्भावपूर्ण उपयोग',
      'guide17Body':
          'रिकॉर्ड बनाने, संरचित शिकायत दाखिल करने और IC या पुलिस प्रक्रिया की तैयारी के लिए पोर्टल का उपयोग करें। खतरे में पहले आपातकालीन सहायता लें।',
      'safeRouteChanged': 'सुरक्षित मार्ग बदल गया',
      'dailyRouteGuard': 'दैनिक मार्ग सुरक्षा',
      'routeGuardDialogTitle': 'दैनिक मार्ग बदल गया',
      'routeGuardDialogMessage':
          'आप अपने सामान्य मार्ग से हट गए हैं। कृपया पुष्टि करें कि आप सुरक्षित हैं।',
      'routeGuardConfirmWithin': '{seconds} सेकंड के भीतर पुष्टि करें।',
      'routeGuardDeviationMeters':
          'आपके सामान्य मार्ग से लगभग {meters} मीटर दूर।',
      'routeGuardLearningRoute': 'मार्ग सीख रहा है',
      'routeGuardRoutinesLearned': '{count} दिनचर्या सीखी गई',
      'routeGuardIntelligenceLimited': 'क्षेत्र डेटा सीमित',
      'routeGuardMapRouteActive': 'मानचित्र मार्ग सक्रिय',
      'safetyVerdictSafe': 'आम तौर पर सुरक्षित',
      'safetyVerdictSafeSummary':
          'आपके लाइव स्थान के आधार पर यह क्षेत्र अभी सामान्य रूप से सुरक्षित लगता है।',
      'safetyVerdictCaution': 'सावधानी बरतें',
      'safetyVerdictCautionSummary':
          'यहां अतिरिक्त सावधानी बरतें—आसपास कुछ जोखिम संकेत मिले हैं।',
      'safetyVerdictHighRisk': 'उच्च चिंता',
      'safetyVerdictHighRiskSummary':
          'यह क्षेत्र अभी सुरक्षित नहीं लग सकता, विशेषकर महिलाओं और बुजुर्ग उपयोगकर्ताओं के लिए।',
      'safetyVerdictMonitoring': 'अभी सीख रहा है',
      'safetyVerdictMonitoringSummary':
          'लाइव क्षेत्र जानकारी अभी बन रही है। हम आपके आसपास सीखते समय सतर्क रहें।',
      'safetyWhyNotSafeTitle': 'यह क्षेत्र सुरक्षित क्यों नहीं लग सकता',
      'safetyReasonDrugActivity':
          'इस क्षेत्र में हाल ही में नशीले पदार्थ से जुड़ी गतिविधि रिपोर्ट हुई है।',
      'safetyReasonChainSnatching':
          'आसपास चेन-snatching के मामले दर्ज हुए हैं।',
      'safetyReasonTheftProne':
          'यह हिस्सा चोरी से जुड़ी घटनाओं के लिए जाना जाता है।',
      'safetyReasonHarassmentReports':
          'आसपास उत्पीड़न या हमले की रिपोर्ट दर्ज हुई हैं।',
      'safetyReasonPoorLighting':
          'खराब सड़क रोशनी से यहां दृश्यता कम हो सकती है।',
      'safetyReasonLowFootfall':
          'कम पैदल यातायात से यह क्षेत्र अलग-थलग महसूस हो सकता है।',
      'safetyReasonCrimeActivity':
          'आसपास की घटनाएं अभी भी बढ़ी हुई हैं।',
      'safetyReasonLimitedSupport':
          'आसपास सीमित आपातकालीन सहायता बिंदु त्वरित मदद में देरी कर सकते हैं।',
      'safetyReasonNightRisk':
          'रात के समय दृश्यता और सार्वजनिक गतिविधि कम हो जाती है।',
      'safetyReasonGpsLimited':
          'लाइव स्थान सटीकता सीमित है; GPS सुधरने पर आकलन अपडेट हो सकता है।',
      'safetyReasonUnsafeNightlife':
          'असुरक्षित नाइटलाइफ या red-light गतिविधि यहां जोखिम बढ़ा सकती है।',
      'safetyReasonGeneralCaution':
          'इस क्षेत्र में अतिरिक्त सावधानी की सलाह है।',
      'safetyReasonLimitedData':
          'सत्यापित लाइव क्षेत्र डेटा सीमित है — यहां अतिरिक्त सतर्क रहें।',
      'routeVerdictChanged': 'मार्ग बदला',
      'routeVerdictChangedSummary':
          'आप अपने सामान्य मार्ग से हट गए हैं। कृपया पुष्टि करें कि आप सुरक्षित हैं।',
      'routeVerdictLearning': 'मार्ग सीख रहा है',
      'routeVerdictLearningSummary':
          'दैनिक मार्ग सुरक्षा आपके लाइव GPS से यात्रा पैटर्न सीख रही है।',
      'routeVerdictOnTrack': 'सामान्य मार्ग पर',
      'routeVerdictOnTrackSummary':
          'आप अपने सीखे हुए सुरक्षित दैनिक मार्ग पर हैं।',
      'routeVerdictCaution': 'मार्ग सावधानी',
      'routeVerdictCautionSummary':
          'कुछ मार्ग स्थितियों पर अभी अतिरिक्त ध्यान देना जरूरी है।',
      'routeVerdictAlert': 'मार्ग चेतावनी',
      'routeVerdictAlertSummary':
          'आपका वर्तमान मार्ग आपके सामान्य सुरक्षित पैटर्न से मेल नहीं खाता।',
      'refresh': 'रीफ़्रेश',
      'openMap': 'मानचित्र खोलें',
      'resetHomeWorkplaceRouteLearning': 'घर-कार्यस्थल मार्ग सीखना रीसेट करें',
      'homeWorkplaceRouteLearningReset':
          'घर-कार्यस्थल मार्ग सीखना रीसेट हो गया।',
      'safetyCheckEndsIn': 'सुरक्षा जांच समाप्त होगी',
      'unlessYouConfirm': 'जब तक आप पुष्टि नहीं करते।',
      'imSafe': 'मैं सुरक्षित हूँ',
      'pleaseFillAllRequiredDetails': 'कृपया सभी आवश्यक विवरण भरें।',
      'complaintSubmittedSuccessfully': 'शिकायत सफलतापूर्वक सबमिट की गई।',
      'submissionFailedTryAgain': 'सबमिशन विफल रहा। कृपया पुनः प्रयास करें।',
      'openDetailedPoshActGuide': 'विस्तृत POSH अधिनियम मार्गदर्शिका खोलें',
      'clearPreviousQuizToUnlockThisLevel':
          'इस स्तर को अनलॉक करने के लिए पिछला क्विज़ साफ़ करें।',
      'previous': 'पिछला',
      'retryQuiz': 'क्विज़ फिर से प्रयास करें',
      'pleaseAnswerEveryQuestionFirst': 'कृपया पहले हर प्रश्न का उत्तर दें।',
      'pleaseAnswerThisQuestionBeforeContinuing':
          'कृपया जारी रखने से पहले इस प्रश्न का उत्तर दें।',
      'currentLevel': 'वर्तमान स्तर',
      'detailedPoshActGuide': 'विस्तृत POSH अधिनियम मार्गदर्शिका',
      'cyberLawHubTitle': 'साइबर क्राइम कानून पुस्तकालय',
      'cyberLawHubSubtitle': 'अपने अधिकार जानें। कानून जानें। लड़ना सीखें।',
      'cyberLawHelplineTitle': 'आपातकालीन हेल्पलाइन',
      'cyberLawHelplineDesc': 'साइबर क्राइम: 1930  |  महिला: 181  |  बाल: 1098  |  पुलिस: 112',
      'cyberLawOverviewHeader': 'अवलोकन',
      'cyberLawActsHeader': 'लागू कानून एवं धाराएं',
      'cyberLawPunishmentHeader': 'कानूनी दंड',
      'cyberLawWhatToDoHeader': 'यदि आप पीड़ित हैं तो क्या करें',
      'cyberLawReportHeader': 'शिकायत कहाँ करें',
    },
    'mr': {
      'appTitle': 'सुरक्षा',
      'greetingHello': 'नमस्कार',
      'welcomeBack': 'परत स्वागत आहे',
      'signInToContinue': 'आपली सुरक्षा यात्रा सुरू ठेवण्यासाठी साइन इन करा',
      'emailOrPhone': 'ईमेल किंवा फोन नंबर',
      'password': 'पासवर्ड',
      'login': 'लॉगिन',
      'emergencyContactsInformed': 'आपत्कालीन संपर्कांना सूचित केले',
      'liveLocationSharedWith': 'लाइव्ह स्थान शेअर केले गेले आहे:',
      'fetchingLocation': 'स्थान शोधत आहे...',
      'liveFeedActive': 'लाइव्ह फीड सक्रिय ({time})',
      'startingLiveTransmission': 'लाइव्ह ट्रान्समिशन सुरू केले जात आहे...',
      'liveTransmissionPaused': 'लाइव्ह ट्रान्समिशन थांबलं आहे',
      'emergencyModeActive': 'आपत्कालीन मोड सक्रिय',
      'helpOnTheWay': 'मदत येत आहे. तुमचं लाइव्ह स्थान शेअर केलं जात आहे.',
      'currentLocation': 'सध्याचे स्थान',
      'status': 'स्थिती',
      'iAmSafeCancelSos': 'मी सुरक्षित आहे - SOS रद्द करा',
      'myProfile': 'माझे प्रोफाइल',
      'profileSubtitle': 'तुमची सुरक्षा ओळख, भाषा आणि आपत्कालीन तयारी सांभाळा.',
      'profileOverview': 'प्रोफाइल सारांश',
      'profileStatsTitle': 'तुमचा सुरक्षा स्नॅपशॉट',
      'profileHeroCta': 'जलद मदतीसाठी प्रोफाइल वैयक्तिक बनवा.',
      'languageSelectionTitle': 'ॲपची भाषा निवडा',
      'darkMode': 'डार्क मोड',
      'darkModeSubtitleOn': 'डार्क ब्लू थीम',
      'darkModeSubtitleOff': 'हलकी शांत थीम',
      'language': 'भाषा',
      'contentLanguage': 'अॅपमधील मजकुराची भाषा',
      'english': 'इंग्रजी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'editProfile': 'प्रोफाइल संपादित करा',
      'editPhoneNumber': 'फोन नंबर संपादित करा',
      'addEmergencyContactTitle': 'आपत्कालीन संपर्क जोडा',
      'editEmergencyContactTitle': 'आपत्कालीन संपर्क संपादित करा',
      'editProfileDetails': 'प्रोफाइल तपशील संपादित करा',
      'editMedicalProfile': 'मेडिकल प्रोफाइल संपादित करा',
      'fullName': 'पूर्ण नाव',
      'email': 'ईमेल',
      'phone': 'फोन नंबर',
      'relation': 'नाते',
      'name': 'नाव',
      'bloodGroup': 'ब्लड ग्रुप',
      'allergies': 'अॅलर्जी',
      'medicalConditions': 'आरोग्यविषयक स्थिती',
      'currentMedications': 'सध्याची औषधे',
      'phoneNumber': 'फोन नंबर',
      'notProvided': 'उपलब्ध नाही',
      'emergencyContacts': 'आपत्कालीन संपर्क',
      'contactsSaved': 'संपर्क जतन केले',
      'emergencyContactList': 'आपत्कालीन संपर्क यादी',
      'addEmergencyContact': 'आपत्कालीन संपर्क जोडा',
      'addNewContact': 'नवीन संपर्क जोडा',
      'logoutSession': 'लॉगआउट',
      'save': 'जतन करा',
      'cancel': 'रद्द करा',
      'ok': 'ठीक आहे',
      'saving': 'जतन करत आहे...',
      'saved': 'जतन झाले',
      'screamDetection': 'चिघाड ओळख',
      'screamDetectionEnabled': 'चिघाड ओळख सुरू केली.',
      'screamDetectionDisabled': 'चिघाड ओळख बंद केली.',
      'screamDetectionEnableFailed': 'चिघाड ओळख सुरू करता आली नाही.',
      'distressSensitivity': 'ओळख संवेदनशीलता',
      'distressSensitivitySubtitle':
          'उच्च = हळuva चिघाड; निम्न = कमी चुकीचे अलर्ट.',
      'distressSensitivity_low': 'निम्न',
      'distressSensitivity_medium': 'मध्यम',
      'distressSensitivity_high': 'उच्च',
      'distressTestMode': 'चाचणी मोड (SOS नाही)',
      'distressTestModeSubtitle':
          'चिघाड/शब्द ओळखा पण SOS पाठवू नका. अचूकता तपासण्यासाठी.',
      'distressLastHeard': 'शेवटी ऐकले',
      'microphoneSafetyMonitorActive': 'मायक्रोफोन सुरक्षा मॉनिटर सुरू आहे.',
      'microphoneSafetyMonitorInactive': 'हे बंद असताना मायक्रोफोन बंद राहतो.',
      'impactDetection': 'आघात ओळख',
      'impactDetectionEnabled': 'आघात ओळख सुरू केली.',
      'impactDetectionDisabled': 'आघात ओळख बंद केली.',
      'impactDetectionEnableFailed': 'आघात ओळख सुरू करता आली नाही.',
      'motionSensorsActive': 'मोशन सेन्सर अचानक आघातासाठी लक्ष ठेवत आहेत.',
      'motionSensorsInactive': 'हे बंद असताना मोशन सेन्सर बंद राहतात.',
      'phoneNumberRequired': 'फोन नंबर आवश्यक आहे.',
      'nameAndPhoneRequired': 'नाव आणि फोन नंबर आवश्यक आहेत.',
      'duplicatePhoneNumber': 'हा फोन नंबर आधीच जतन केला आहे.',
      'savedLocallyRetryLater':
          'स्थानिकरित्या जतन केले. सर्व्हर सिंक नंतर पुन्हा प्रयत्न करेल.',
      'photoSavedLocally': 'फोटो स्थानिकरित्या जतन केला.',
      'serverSyncWillRetryLater': 'सर्व्हर सिंक नंतर पुन्हा प्रयत्न करेल.',
      'profileSavedTitle': 'प्रोफाइल जतन झाले',
      'profileSavedMessage': 'तुमची माहिती सुरक्षितपणे जतन झाली आहे.',
      'medicalSavedTitle': 'मेडिकल प्रोफाइल जतन झाले',
      'medicalSavedMessage': 'तुमची मेडिकल माहिती यशस्वीरित्या अपडेट झाली आहे.',
      'contactSavedTitle': 'संपर्क जतन झाला',
      'contactSavedMessage':
          'आपत्कालीन संपर्क तपशील यशस्वीरित्या अपडेट झाले आहेत.',
      'draftSavedTitle': 'ड्राफ्ट जतन झाला',
      'draftSavedMessage': 'तुमचा ड्राफ्ट या डिव्हाइसवर सुरक्षित झाला आहे.',
      'emergencyServices': 'आपत्कालीन सेवा',
      'communityAlerts': 'समुदाय सूचना',
      'safetyRegionLabel': 'प्रदेश',
      'safetyDataDisclaimerTitle': 'डेटा स्रोत',
      'safetyConfidenceSuffix': 'विश्वास',
      'safetySourceOpenStreetMap': 'OpenStreetMap',
      'safetySourceSunset': 'सूर्यास्त API',
      'safetySourceCrowd': 'अनाम गर्दी',
      'safetySourceSurakshaReports': 'Suraksha अहवाल',
      'safetySourceSurakshaEngine': 'Suraksha इंजिन',
      'safetySourceSurakshaCommunity': 'समुदाय प्रमाणित',
      'safetySourceRegionalGuidance': 'प्रादेशिक मार्गदर्शन',
      'safetyDimCrime': 'गुन्हे',
      'safetyDimInfrastructure': 'प्रकाश',
      'safetyDimSupport': 'मदत',
      'safetyDimVisibility': 'दृश्यमानता',
      'safetyDimTemporal': 'वेळ',
      'safetySourceGridModel': 'ग्रिड मॉडेल',
      'safetySourceOpenDataDistrict': 'जिल्हा ओपन डेटा',
      'safetyUpdatedAgo': 'अपडेट',
      'aiSummaryFromGemini': 'AI सारांश (Gemini)',
      'aiSummaryFromTemplate': 'AI सारांश (ऑफलाइन)',
      'journeySafetyAlerts': 'प्रवास सुरक्षा सूचना',
      'journeySafetyAlertsSubtitle':
          'नेव्हिगेशन दरम्यान उच्च जोखीम क्षेत्रात प्रवेश केल्यावर पुश आणि इन-अॅप सूचना.',
      'journeyRerouteHint': 'अधिक सुरक्षित मार्ग उपलब्ध',
      'tapForAlerts': 'अलर्ट पाहण्यासाठी टॅप करा',
      'tapRefreshTryAgain': 'पुन्हा प्रयत्न करण्यासाठी रिफ्रेश टॅप करा',
      'loadingLiveAreaAlerts': 'लाईव्ह परिसर अलर्ट लोड होत आहेत...',
      'checkingTrafficTransportNearbyActivity':
          'वाहतूक, परिवहन आणि जवळची हालचाल तपासत आहोत',
      'liveAlertsWillAppearHere': 'लाईव्ह अलर्ट इथे दिसतील',
      'keepGpsOnForRealtimeCommunityUpdates':
          'रीअलटाइम community updates साठी GPS चालू ठेवा',
      'locationRequiredTitle': 'स्थान आवश्यक आहे',
      'locationRequiredMessage':
          'Suraksha वापरण्यासाठी GPS आणि स्थान परवानगी आवश्यक आहे. सुरू ठेवण्यासाठी त्यांना सक्षम करा.',
      'locationAutoRefreshMessage':
          'स्थान सक्षम केल्यावर सेवा स्वयंचलितपणे रीफ्रेश होतील.',
      'retryLocation': 'स्थान सेटअप पुन्हा प्रयत्न करा',
      'womenHelpline': 'महिला हेल्पलाइन',
      'nearbyServices': 'जवळच्या सेवा',
      'nearbyHospitals': 'जवळची रुग्णालये',
      'policeStations': 'पोलीस ठाणे',
      'nearbyWashrooms': 'जवळचे वॉशरूम',
      'nearbyBloodBanks': 'जवळच्या रक्तपेढ्या',
      'nearbyPharmacies': 'जवळच्या फार्मसी',
      'tapToLoadNearby': 'जवळच्या सेवा लोड करण्यासाठी बटण दाबा.',
      'noNearbyPlaces': '5 किमी परिसरात कोणतीही जागा सापडली नाही.',
      'safeZoneActive': 'सुरक्षा प्राधान्य',
      'helloKaveri': 'नमस्कार, कावेरी',
      'openSafetyMap': 'सुरक्षा नकाशा उघडा',
      'openSafetyMapConfirm': 'हे ठिकाण नकाशावर पाहायचे आहे का?',
      'mapOpenChoiceTitle': 'ठिकाण उघडा',
      'mapOpenChoiceMessage': 'हे ठिकाण कसे उघडायचे ते निवडा.',
      'mapOpenChoiceSuraksha': 'सुरक्षा नकाशा',
      'mapOpenChoiceGoogle': 'गुगल मॅप्स',
      'yes': 'हो',
      'no': 'नाही',
      'couldNotOpenDialer': 'डायलर उघडता आला नाही',
      'policeEmergency': 'पोलीस अपातकालीन',
      'scanningNearbyPlaces': 'जवळच्या ठिकाणांची स्कॅनिंग केली जात आहे...',
      'nearbyResultsCount': '{count} जवळचे परिणाम',
      'chooseServiceToScanYourArea':
          'तुमचा सध्याचा परिसर स्कॅन करण्यासाठी खाली एक सेवा निवडा.',
      'cyberCrimeProtection': 'सायबर क्राइम संरक्षण',
      'aiAssist': 'एआय सहाय्य',
      'report': 'रिपोर्ट',
      'vault': 'वॉल्ट',
      'learn': 'शिका',
      'deepfake': 'डीपफेक',
      'aiScamFraudAssistantTitle': 'एआय घोटाळा व फसवणूक ओळख सहाय्यक',
      'pasteEvidenceContext':
          'संदिग्ध संदेश, दुवे, चाट किंवा प्रश्न पेस्ट करा. प्रमाणासाठी स्क्रीनशॉट जोडाः',
      'suspiciousMessageLabel': 'संदिग्ध संदेश, ईमेल किंवा चाट',
      'pasteFullMessageHereHint': 'पूर्ण संदेश इथे पेस्ट करा...',
      'suspiciousLinksLabel': 'संदिग्ध दुवे',
      'urlHint': 'https://example.com, bit.ly/...',
      'askQuestionLabel': 'एक प्रश्न विचारावा',
      'scamQuestionHint': 'हे स्वरूप फसवणूक आहे का? ही प्रोफाइल खोटी आहे का?',
      'attachScreenshot': 'स्क्रीनशॉट जोडा',
      'analyze': 'विश्लेषण करा',
      'selectIncidentType': 'घटनेचा प्रकार निवडा',
      'attachScreenshotsOrProof': 'स्क्रीनशॉट किंवा व्यवहार पुरावा जोडा',
      'incidentDescription': 'घटनेचे वर्णन',
      'incidentDetailsHint':
          'काय घडले ते, वापरकर्तानावे, रक्कम, धमक्या आणि प्लॅटफॉर्म वर्णन करा.',
      'suspectContactLabel': 'फोन/ईमेल/प्रोफाइल दुवा',
      'suspectContactHint': 'शंकित संपर्क किंवा प्रोफाइल URL',
      'transactionIdLabel': 'व्यवहार आयडी',
      'transactionIdHint': 'आर्थिक फसवणुकीसाठी UPI/ref क्र. असल्यास',
      'incidentTime': 'घटनेचा वेळ: {time}',
      'pdfReady': 'PDF तयार',
      'newReport': 'नवी रिपोर्ट',
      'saveDraft': 'ड्राफ्ट जतन करा',
      'reportGenerated': 'रिपोर्ट तयार झाली.',
      'draftSavedOnline': 'ड्राफ्ट ऑनलाइन साठवला.',
      'couldNotSubmitOnline': 'ऑनलाइन सबमिट करू शकले नाही. पुन्हा प्रयत्न करा.',
      'secureEvidenceVault': 'सुरक्षित साक्ष्य वॉल्ट',
      'uploadTagSearchPackageEvidence':
          'साइबर साक्ष्य अपलोड करा, टॅग करा, शोधा आणि पॅकेज करा. बॅकएंड फाइल AES एन्क्रिप्टेड आहेत.',
      'takeQuiz': 'क्विझ घ्या',
      'progressBadge': '{percent}% पूर्ण | बॅज: {badge}',
      'cyberDefender': 'सायबर डिफेंडर',
      'cyberLearner': 'सायबर लर्नर',
      'deepfakeSubtitle':
          'जागरूकता, आपत्कालीन प्रतिक्रिया, कायदेशीर मार्गदर्शन आणि हेल्पलाइन प्रवेश.',
      'deepfakeWarning':
          'कोणीतरी मॉर्फ/खाजगी मीडिया लीक करण्याची धमकी देत असल्यास, पैसे देऊ नका किंवा वाटाघाटी करू नका. पुरावे जतन करा आणि लवकर रिपोर्ट करा.',
      'emergencyActions': 'आपत्कालीन क्रिया',
      'call1930': '1930 कॉल करा',
      'police100': 'पोलीस 100',
      'cyberPortal': 'सायबर पोर्टल',
      'uploadEncryptedEvidence': 'एन्क्रिप्टेड पुरावा अपलोड करा',
      'noFilesSelectedYet': 'अद्याप कोणत्याही फाईल्स निवडल्या नाहीत.',
      'generate': 'निर्माण करा',
      'generatedComplaint': 'निर्मित तक्रार',
      'reportSummaryUnavailable': 'रिपोर्ट सारांश उपलब्ध नाही.',
      'pdfPayloadGenerated':
          'PDF पेलोड तयार. निर्यात एकीकरण बॅकएंड प्रतिसादापासून साठवू/शेअर करू शकते.',
      'evidenceTitleLabel': 'साक्ष्य शीर्षक',
      'evidenceTitleHint': 'धमकी स्क्रीनशॉट, UPI पुरावा...',
      'category': 'श्रेणी',
      'private': 'खाजगी',
      'tags': 'टॅग',
      'tagsHint': 'ब्लॅकमेल, इंस्टाग्राम, पेमेंट',
      'finish': 'पूर्ण',
      'searchVault': 'वॉल्ट शोधा',
      'searchByTitle': 'शीर्षकानुसार शोधा',
      'noEvidenceFound':
          'कोणतेही साक्ष्य सापडले नाही. आपले सुरक्षित वॉल्ट सुरू करण्यासाठी साक्ष्य अपलोड करा.',
      'sessionExpiredSignIn': 'सत्र संपले. कृपया पुन्हा साइन इन करा.',
      'loginRequiredCyber': 'सुरक्षित सायबर वैशिष्ट्यांसाठी पुन्हा लॉगिन करा.',
      'fileTooLarge10Mb': 'फाइल खूप मोठी आहे. कमाल 10 MB.',
      'networkServerIssue': 'नेटवर्क किंवा सर्व्हर समस्या. पुन्हा प्रयत्न करा.',
      'couldNotSharePdf': 'PDF शेअर होऊ शकले नाही.',
      'couldNotExportEvidence': 'साक्ष्य पॅकेज निर्यात होऊ शकले नाही.',
      'riskLevel': 'धोका पातळी',
      'recommendedActions': 'शिफारस केलेली कृती',
      'safetyTips': 'सुरक्षा टिपा',
      'encrypted': 'एन्क्रिप्टेड',
      'notEncrypted': 'एन्क्रिप्टेड नाही',
      'linkedToReport': 'अहवालाशी जोडले',
      'preview': 'पूर्वावलोकन',
      'download': 'डाउनलोड',
      'delete': 'हटवा',
      'noUnlinkedEvidence': 'वॉल्टमध्ये अनलिंक्ड साक्ष्य नाही.',
      'minDescriptionChars': 'किमान 10 अक्षरे वर्णन जोडा.',
      'draftPendingDetails': 'ड्राफ्ट अहवालाचे तपशील प्रलंबित.',
      'evidenceFilesSecured': '{count} साक्ष्य फाइल(स) वॉल्टमध्ये सुरक्षित.',
      'vaultEvidenceLinked': '{count} वॉल्ट आयटम अहवालाशी जोडले.',
      'summaryStep': 'सारांश',
      'myReports': 'माझे अहवाल',
      'noSubmittedReportsYet': 'अद्याप कोणतेही अहवाल नाहीत.',
      'draft': 'ड्राफ्ट',
      'pickFromGallery': 'गॅलरी',
      'pickFile': 'फाइल निवडा',
      'attachFromVault': 'वॉल्टमधून',
      'vaultItemsSelected': '{count} वॉल्ट आयटम निवडले',
      'uploadingEvidence': 'साक्ष्य अपलोड होत आहे...',
      'selectVaultEvidence': 'वॉल्ट साक्ष्य निवडा',
      'analyzeInputRequired': 'संदेश, लिंक, प्रश्न पेस्ट करा किंवा स्क्रीनशॉट जोडा.',
      'clearScreenshot': 'स्क्रीनशॉट काढा',
      'screenshotTextExtracted': 'स्क्रीनशॉटमधून मजकूर काढला',
      'evidenceEncryptedSaved': 'साक्ष्य एन्क्रिप्ट करून जतन केले.',
      'uploadFailed': 'अपलोड अयशस्वी.',
      'previewFailed': 'पूर्वावलोकन अयशस्वी.',
      'downloadFailed': 'डाउनलोड अयशस्वी.',
      'deleteEvidenceTitle': 'साक्ष्य हटवायचे?',
      'deleteEvidenceConfirm': '"{title}" वॉल्टमधून काढायचे?',
      'evidenceDeleted': 'साक्ष्य हटवले.',
      'deleteFailed': 'हटवणे अयशस्वी.',
      'exportFailed': 'निर्यात अयशस्वी.',
      'exportEvidencePackage': 'साक्ष्य पॅकेज निर्यात',
      'filterAll': 'सर्व',
      'filterLinked': 'जोडलेले',
      'filterUnlinked': 'अनलिंक्ड',
      'reportDetails': 'अहवाल तपशील',
      'linkedEvidence': 'जोडलेले साक्ष्य',
      'noLinkedEvidence': 'या अहवालाशी साक्ष्य जोडलेले नाही.',
      'digitalSafetyLearningHub': 'डिजिटल सुरक्षा शिक्षण केंद्र',
      'learningHubSubtitle': 'फिशिंग, UPI, गोपनीयता आणि डीपफेक कौशल्ये विकसित करा.',
      'cyberSafetyScore': 'सायबर सुरक्षा स्कोअर',
      'cyberSafetyScoreUpdated': 'सायबर सुरक्षा स्कोअर: {score}',
      'catFinancialFraud': 'आर्थिक फसवणूक',
      'catCyberStalking': 'सायबर स्टॉकिंग',
      'catOnlineBullying': 'ऑनलाइन बुलिंग',
      'catIdentityTheft': 'ओळख चोरी',
      'catSocialMediaHarassment': 'सोशल मीडिया छळ',
      'catHarassment': 'छळ',
      'catBlackmail': 'ब्लॅकमेल',
      'catFakeProfile': 'बनावट प्रोफाइल',
      'catDeepfakeThreat': 'डीपफेक धमकी',
      'catDeepfakeScam': 'डीपफेक फसवणूक',
      'catFakeJobScam': 'बनावट नोकरी फसवणूक',
      'catUpiFraud': 'UPI फसवणूक',
      'catOther': 'इतर',
      'evidenceCatAll': 'सर्व',
      'evidenceCatScreenshot': 'स्क्रीनशॉट',
      'evidenceCatAudio': 'ऑडिओ',
      'evidenceCatThreatMessage': 'धमकी संदेश',
      'evidenceCatImage': 'प्रतिमा',
      'evidenceCatTransactionProof': 'व्यवहार पुरावा',
      'evidenceCatDocument': 'दस्तऐवज',
      'evidenceCatOther': 'इतर',
      'multiSelectNone': 'काहीही निवडले नाही',
      'multiSelectCount': '{count} निवडले',
      'filterCategories': 'श्रेणी फिल्टर',
      'filterLinkStatus': 'लिंक स्थिती',
      'additionalCategoriesNote': 'अतिरिक्त घटना प्रकार',
      'configureServer': 'सर्व्हर कॉन्फिगर करा',
      'configureServerHint':
          'PC IP प्रविष्ट करा जिथे backend चालत आहे. उदा: http://192.168.1.5:5000/api',
      'serverUrlHint': 'http://192.168.1.5:5000/api',
      'serverUrlSaved': 'सर्व्हर URL जतन केला. कनेक्शन पुन्हा प्रयत्न...',
      'cannotReachServer':
          'सर्व्हरशी कनेक्ट होता आले नाही. कृपया इंटरनेट तपासा आणि पुन्हा प्रयत्न करा.',
      'fixConnection': 'पुन्हा प्रयत्न करा',
      'deepfakeEmergencySupportTitle': 'डीपफेक व मोर्फ्ड इमेज तातडीची मदत',
      'medicalHealthVault': 'मेडिकल हेल्थ वॉल्ट',
      'keepEmergencyMedicalInformationOrganized':
          'आपातकालीन वैद्यकीय माहिती जलद वापरासाठी व्यवस्थित ठेवा.',
      'emergencyMedicalId': 'आपत्कालीन वैद्यकीय आयडी',
      'scanInCaseOfMedicalEmergency': 'वैद्यकीय आपातकाळाच्या बाबतीत स्कॅन करा',
      'medicalProfileSaved': 'वैद्यकीय प्रोफाइल जतन केली गेली',
      'medicalDetailsReady':
          'आपली वैद्यकीय माहिती आपत्कालीन वापरासाठी तयार आहे.',
      'savedLocallyOnThisDevice': 'हे डिव्हाइसवर स्थानिकपणे जतन केले.',
      'medicalProfileSavedLocallySyncRetryLater':
          'वैद्यकीय प्रोफाइल स्थानिकपणे जतन केली गेली. सिंक नंतर पुन्हा प्रयत्न करेल.',
      'certificateDetails': 'प्रमाणपत्र तपशील',
      'issuedOn': '{date} ला जारी करण्यात आले',
      'poshCertifiedMessage':
          'आपण सर्व तीन क्विझ पातळ्या पूर्ण केल्या आहेत आणि मजबूत POSH कायदा ज्ञान दर्शविले आहे.',
      'validForPoshCertificate':
          'वैध: POSH कायदा जागरूकता आणि कार्यस्थळ सुरक्षितता प्रशिक्षणासाठी',
      'safeZoneUpdatedNearby': 'जवळ सुरक्षित क्षेत्र अपडेट झाले',
      'crowdedAreaWarning': 'गर्दीच्या भागाची चेतावणी',
      'minsAgo2': '2 मिनिटांपूर्वी',
      'minsAgo15': '15 मिनिटांपूर्वी',
      'map': 'नकाशा',
      'medical': 'मेडिकल',
      'cyber': 'सायबर',
      'poshPortal': 'POSH पोर्टल',
      'study': 'अभ्यास',
      'quizzes': 'क्विझ',
      'complaint': 'तक्रार',
      'poshActLearningHub': 'POSH कायदा अभ्यास केंद्र',
      'poshStudy1Title': 'POSH कायदा काय कव्हर करतो',
      'poshStudy1Bullet1':
          'POSH कायदा कार्यस्थळी महिला विरोधी लैंगिक छळ (2013) यांचा अंतर्भाव करतो.',
      'poshStudy1Bullet2':
          'हा सन्मान, समानता आणि सुरक्षित कामाच्या अटींचे रक्षण करतो.',
      'poshStudy1Bullet3':
          'हा सार्वजनिक व खासगी कार्यस्थळे, कार्यालये, दुकाने, रुग्णालये, शाळा, NGO आणि नियोक्ता प्रदान केलेले प्रवास यावर लागू होतो.',
      'poshStudy1Bullet4':
          'कायदा कर्मचारी, प्रशिक्षार्थी, इंटर्न, करार कर्मचारी, स्वयंसेवक आणि कार्यस्थलावर येणाऱ्या अभ्यागतांना कव्हर करतो.',
      'poshStudy1Bullet5':
          'लैंगिक स्वरूपाचा अनिच्छित वागणूक मौखिक, लिखित, डिजिटल किंवा शारीरिक असू शकतो.',
      'poshStudy1Bullet6':
          'उदाहरण: अनिच्छित स्पर्श, लैंगिक टिप्पणी, संदेश, सतत छळ किंवा अश्लील सामग्री दाखवणे.',
      'poshStudy2Title': 'तक्रार प्रक्रिया आणि आंतरिक समिती (IC)',
      'poshStudy2Bullet1':
          'तक्रार सामान्यतः घटना घडल्यापासून 3 महिन्यांमध्ये लेखी स्वरूपात नोंदवावी.',
      'poshStudy2Bullet2':
          '10 किंवा अधिक कर्मचारी असलेल्या कार्यस्थळी आंतरिक समिती योग्य रचनेनुसार असावी.',
      'poshStudy2Bullet3':
          'समितीत सामान्यतः वरिष्ठ महिला अध्यक्ष, कर्मचारी सदस्य आणि बाह्य सदस्य समाविष्ट असतात.',
      'poshStudy2Bullet4':
          'समेट फक्त तक्रारकर्त्याने हवे असल्यास वापरता येतो; हे जबरदस्तीचे नसावे.',
      'poshStudy2Bullet5':
          'जर समेट झाले नाही तर IC निष्पक्ष चौकशी करते जिथे दोन्ही बाजू ऐकल्या जातात.',
      'poshStudy2Bullet6': 'प्रक्रिया गोपनीय, लेखी आणि दस्तऐवजीकृत राहावी.',
      'poshStudy3Title': 'पुरावे, सुरक्षा आणि नियोक्त्याचे कर्तव्य',
      'poshStudy3Bullet1':
          'चॅट, ईमेल, स्क्रीनशॉट, कॉल लॉग, साक्षीदारांची नावे, तारखा आणि ठिकाणे नोंद ठेवा.',
      'poshStudy3Bullet2':
          'अंतरिम मदत म्हणून बदली, रजा, संपर्क-निषेध किंवा रिपोर्टिंग-लाइन बदल समाविष्ट असू शकतो.',
      'poshStudy3Bullet3':
          'जर तथ्यांनी गुन्हे दाखवले तर POSH प्रक्रियेव्यतिरिक्त पोलिस तक्रार/FIR नोंदवता येऊ शकते.',
      'poshStudy3Bullet4':
          'नियोक्त्यांनी धोरण प्रदर्शित करावे, कर्मचारी प्रशिक्षण द्यावा, IC ला समर्थन द्यावे आणि शिफारसी लागू कराव्यात.',
      'poshStudy3Bullet5':
          'गोपनीयता तक्रारकर्ता, प्रतिवादी, साक्षीदार आणि कार्यवाहीवर लागू होते.',
      'poshStudy3Bullet6':
          'एक तक्रार फक्त म्हणून खोटी नाही की ती सिद्ध केली जाऊ शकली नाही; जानबूझून खोटेपणा वेगळा प्रकरण आहे.',
      'poshStudy4Title': 'महत्वाचे POSH मर्यादा',
      'poshStudy4Bullet1':
          'अनावश्यक वैयक्तिक वाद किंवा जाणूनबुजून बनवलेल्या आरोपांसाठी यंत्रणा वापरू नका.',
      'poshStudy4Bullet2':
          'पुरावे नष्ट करू नका आणि साक्षीदारांवर दबाव आणू नका.',
      'poshStudy4Bullet3':
          'लहान परंतु सतत घडणाऱ्या घटनांकडे दुर्लक्ष करू नका; नमुने महत्त्वाचे आहेत.',
      'poshStudy4Bullet4':
          'तथ्यात्मक, तारीख-निहायत आणि तपशीलवार रिपोर्टिंग वापरा.',
      'poshStudy4Bullet5':
          'तत्काळ धोक्यात असाल तर प्रथम आपत्कालीन सेवा कॉल करा.',
      'poshStudy4Bullet6':
          'POSH पोर्टल शिकण्यासाठी, दस्तऐवजीकरणासाठी आणि संरचित तक्रार तयारीसाठी आहे.',
      'studyFirst': 'आधी अभ्यास करा',
      'readAllSectionsBeforeQuiz1': 'क्विझ 1 पूर्वी सर्व विभाग वाचा',
      'threeLevels': 'तीन स्तर',
      'twentyMcqsEachQuiz': 'प्रत्येक क्विझमध्ये 20 MCQ',
      'quizCertificationTrack': 'क्विझ प्रमाणपत्र ट्रॅक',
      'studyFirstThenClearQuizzesInOrder':
          'आधी अभ्यास करा, मग क्विझ क्रमाने पूर्ण करा.',
      'level': 'स्तर',
      'levelPassed': 'स्तर पूर्ण',
      'passed': 'पूर्ण',
      'available': 'उपलब्ध',
      'locked': 'लॉक',
      'submitQuiz': 'क्विझ सबमिट करा',
      'next': 'पुढे',
      'unlocked': 'अनलॉक',
      'quizNotClearedYet': 'क्विझ अद्याप साफ झालेले नाही',
      'reviewStudy': 'अभ्यास पहा',
      'retry': 'पुन्हा प्रयत्न',
      'viewCertificate': 'प्रमाणपत्र पहा',
      'continueLabel': 'सुरू ठेवा',
      'poshCertified': 'POSH प्रमाणित',
      'fileWorkplaceComplaint': 'कार्यस्थळी तक्रार नोंदवा',
      'fileWorkplaceComplaintSubtitle':
          'तपशीलवार तक्रार नोंद तयार करा आणि पाठवा. तातडीच्या धोक्यात 112 वर कॉल करा.',
      'keepRecordsFactual':
          'तुमची नोंद तथ्यात्मक ठेवा आणि शक्य असल्यास पुरावा जोडा.',
      'yourFullName': 'तुमचे पूर्ण नाव',
      'yourPhoneNumber': 'तुमचा फोन नंबर',
      'yourEmailAddress': 'तुमचा ईमेल पत्ता',
      'accusedPersonName': 'आरोपी व्यक्तीचे नाव',
      'companyWorkplaceName': 'कंपनी / कार्यस्थळाचे नाव',
      'incidentDateDdMmYyyy': 'घटनेची तारीख (DD/MM/YYYY)',
      'incidentLocation': 'घटनेचे ठिकाण',
      'witnessesIfAny': 'साक्षीदार (असल्यास)',
      'detailedIncidentDescription': 'घटनेचे सविस्तर वर्णन',
      'submitting': 'सबमिट करत आहे...',
      'submitComplaint': 'तक्रार सबमिट करा',
      'guideIntro':
          'हे मार्गदर्शक शैक्षणिक आणि कार्यात्मक आहे. हे भारतातील POSH चौकटीतील प्रक्रिया, मर्यादा, दस्तऐवजीकरण आणि पुढील पावले समजावते.',
      'legalDisclaimer':
          'कायदेशीर अस्वीकरण: हे मार्गदर्शक केस-विशिष्ट कायदेशीर सल्ल्याचा पर्याय नाही. महत्त्वाच्या बाबींमध्ये पात्र वकील, HR-POSH तज्ज्ञ किंवा सक्षम प्राधिकरणाचा सल्ला घ्या.',
      'guide1Title': '1. पार्श्वभूमी आणि उद्देश',
      'guide1Body':
          'POSH कायदा कामाच्या ठिकाणी लैंगिक छळ रोखण्यासाठी आणि त्यावर कारवाई करण्यासाठी कायदेशीर चौकट तयार करतो आणि सन्मान व सुरक्षित कामाच्या अटींचे रक्षण करतो.',
      'guide2Title': '2. कुठे लागू होते',
      'guide2Body':
          'हे सार्वजनिक व खासगी कार्यस्थळे, शाळा, रुग्णालये, NGO, क्रीडा व्यवस्था, घरकामाचे संदर्भ आणि नोकरीशी संबंधित प्रवासावर लागू होते.',
      'guide3Title': '3. कोण संरक्षित आहे',
      'guide3Body':
          'हा कायदा मुख्यतः कार्यस्थळी महिलांचे संरक्षण करतो, ज्यात कर्मचारी, प्रशिक्षणार्थी, इंटर्न, स्वयंसेवक, करार कर्मचारी आणि त्या संदर्भातील अभ्यागत समाविष्ट आहेत.',
      'guide4Title': '4. लैंगिक छळ म्हणजे काय',
      'guide4Body':
          'अनाहूत शारीरिक संपर्क, लैंगिक मागण्या, लैंगिक टिप्पणी, अश्लील सामग्री आणि लैंगिक स्वरूपाचे इतर मौखिक, अमौखिक किंवा डिजिटल वर्तन यामध्ये येऊ शकते.',
      'guide5Title': '5. अंतर्गत समिती (IC) आवश्यकता',
      'guide5Body':
          '10 किंवा अधिक कर्मचारी असलेल्या कार्यस्थळी आवश्यक रचनेसह Internal Committee असणे बंधनकारक आहे, ज्यात Presiding Officer आणि बाह्य सदस्य असतो.',
      'guide6Title': '6. तक्रार वेळमर्यादा आणि स्वरूप',
      'guide6Body':
          'तक्रार सामान्यतः 3 महिन्यांच्या आत लेखी दिली जाते. त्यात पक्ष, तारखा, ठिकाण, तथ्ये, साक्षीदार, पुरावे आणि मागितलेली मदत असावी.',
      'guide7Title': '7. संमती/समेट आणि चौकशी',
      'guide7Body':
          'समेट स्वैच्छिक असतो. तो न झाल्यास IC निष्पक्ष चौकशी करते जिथे दोन्ही बाजू ऐकल्या जातात आणि प्रक्रिया लेखी व दस्तऐवजीकृत राहते.',
      'guide8Title': '8. प्रक्रियेतील अंतरिम मदत',
      'guide8Body':
          'अंतरिम मदतीमध्ये बदली, रजा, रिपोर्टिंग लाइन बदल, संपर्क-निषेध, WFH बदल किंवा सुरक्षा मदत समाविष्ट असू शकते.',
      'guide9Title': '9. चौकशी निकाल आणि नियोक्त्याची कारवाई',
      'guide9Body':
          'आरोप सिद्ध झाल्यास, नियमांनुसार इशारा, माफी, समुपदेशन, पदोन्नती/वाढीवर परिणाम, नोकरी समाप्ती किंवा भरपाई सुचवली जाऊ शकते.',
      'guide10Title': '10. पोलिस तक्रार आणि फौजदारी कायदा',
      'guide10Body':
          'POSH हे फौजदारी उपायांचा पर्याय नाही. तथ्यांमधून गुन्हा दिसल्यास, तक्रारदार पोलिस तक्रार किंवा FIR देखील दाखल करू शकतो.',
      'guide11Title': '11. गोपनीयता नियम',
      'guide11Body':
          'पक्ष आणि साक्षीदारांची ओळख, चौकशी तपशील, निष्कर्ष आणि कारवाई गोपनीय ठेवली पाहिजे, जोपर्यंत कायदा वेगळे सांगत नाही.',
      'guide12Title': '12. खोट्या तक्रारी: योग्य कायदेशीर स्थिती',
      'guide12Body':
          'फक्त सिद्ध न झाल्याने तक्रार आपोआप द्वेषपूर्ण ठरत नाही. जाणूनबुजून खोटेपणा किंवा बनावट पुरावा वेगळा निकष आहे.',
      'guide13Title': '13. कायद्याचा गैरवापर कसा करू नये',
      'guide13Body':
          'जाणूनबुजून खोटे आरोप, पुराव्यात फेरफार, साक्षीदारांना प्रभावित करणे किंवा वैयक्तिक वादांसाठी प्रक्रिया वापरणे टाळा.',
      'guide14Title': '14. नियोक्ता अनुपालन सूची',
      'guide14Body':
          'IC योग्यरित्या तयार करा, POSH धोरण प्रकाशित करा, स्टाफला प्रशिक्षण द्या, तक्रार चॅनेल दाखवा, जाँच दस्तऐवजीकरण ठेवा आणि सूड टाळा.',
      'guide15Title': '15. व्यावहारिक पुरावा सूची',
      'guide15Body':
          'चॅट, ईमेल, कॉल लॉग, टाइमस्टॅम्प, साक्षीदारांची नावे, तक्रार इतिहास आणि संबंधित वैद्यकीय/मानसिक आरोग्य नोंदी जपून ठेवा.',
      'guide16Title': '16. अपील आणि इतर उपाय',
      'guide16Body':
          'नियम आणि कायद्याप्रमाणे, पक्ष अपीलीय मार्गांद्वारे निकाल आव्हान देऊ शकतात किंवा बाह्य कायदेशीर उपाय शोधू शकतात.',
      'guide17Title': '17. POSH पोर्टलचा सद्भावपूर्ण वापर',
      'guide17Body':
          'रेकॉर्ड तयार करण्यासाठी, संरचित तक्रार दाखल करण्यासाठी आणि IC किंवा पोलिस प्रक्रियेची तयारी करण्यासाठी पोर्टल वापरा. धोक्यात आधी आपत्कालीन मदत घ्या.',
      'safeRouteChanged': 'सुरक्षित मार्ग बदलला',
      'dailyRouteGuard': 'दैनंदिन मार्ग सुरक्षा',
      'routeGuardDialogTitle': 'दैनंदिन मार्ग बदलला',
      'routeGuardDialogMessage':
          'तुम्ही नेहमीच्या मार्गापासून वळला आहात. तुम्ही सुरक्षित आहात याची खात्री करा.',
      'routeGuardConfirmWithin': '{seconds} सेकंदात पुष्टी करा.',
      'routeGuardDeviationMeters':
          'नेहमीच्या मार्गापासून सुमारे {meters} मीटर दूर.',
      'routeGuardLearningRoute': 'मार्ग शिकत आहे',
      'routeGuardRoutinesLearned': '{count} दिनचर्या शिकल्या',
      'routeGuardIntelligenceLimited': 'क्षेत्र डेटा मर्यादित',
      'routeGuardMapRouteActive': 'नकाशा मार्ग सक्रिय',
      'safetyVerdictSafe': 'सामान्यतः सुरक्षित',
      'safetyVerdictSafeSummary':
          'तुमच्या लाइव्ह स्थानावर आधारित हा परिसर सध्या सामान्यतः सुरक्षित वाटतो.',
      'safetyVerdictCaution': 'सावधानी बाळगा',
      'safetyVerdictCautionSummary':
          'येथे अतिरिक्त सावधानी बाळगा—जवळपास काही धोका संकेत आढळले आहेत.',
      'safetyVerdictHighRisk': 'जास्त चिंता',
      'safetyVerdictHighRiskSummary':
          'हा परिसर सध्या सुरक्षित वाटत नाही, विशेषतः महिला आणि ज्येष्ठ वापरकर्त्यांसाठी.',
      'safetyVerdictMonitoring': 'अजून शिकत आहे',
      'safetyVerdictMonitoringSummary':
          'लाइव्ह परिसर माहिती अजून तयार होत आहे. आम्ही शिकत असताना सजग राहा.',
      'safetyWhyNotSafeTitle': 'हा परिसर सुरक्षित का वाटत नाही',
      'safetyReasonDrugActivity':
          'या परिसरात अलीकडे अमली पदार्थ संबंधित कृती नोंदवल्या गेल्या आहेत.',
      'safetyReasonChainSnatching':
          'जवळपास chain-snatching प्रकरणे नोंदवली गेली आहेत.',
      'safetyReasonTheftProne':
          'हा भाग चोरी संबंधित घटनांसाठी ओळखला जातो.',
      'safetyReasonHarassmentReports':
          'जवळपास छळ किंवा हल्ल्याच्या तक्रारी नोंदवल्या गेल्या आहेत.',
      'safetyReasonPoorLighting':
          'खराब रस्ता प्रकाशामुळे येथे दृश्यता कमी होऊ शकते.',
      'safetyReasonLowFootfall':
          'कमी पादचारी वाहतुकीमुळे हा परिसर एकटा वाटू शकतो.',
      'safetyReasonCrimeActivity':
          'जवळपासच्या घटना अजूनही वाढलेल्या आहेत.',
      'safetyReasonLimitedSupport':
          'जवळपास मर्यादित आपत्कालीन मदत बिंदू त्वरित मदतीस विलंब करू शकतात.',
      'safetyReasonNightRisk':
          'रात्रीच्या वेळी दृश्यता आणि सार्वजनिक हालचाल कमी होते.',
      'safetyReasonGpsLimited':
          'लाइव्ह स्थान अचूकता मर्यादित आहे; GPS सुधारल्यावर मूल्यांकन अद्यतन होऊ शकते.',
      'safetyReasonUnsafeNightlife':
          'असुरक्षित नाइटलाइफ किंवा red-light कृती येथे धोका वाढवू शकते.',
      'safetyReasonGeneralCaution':
          'या परिसरात अतिरिक्त सावधानी घेण्याची शिफारस आहे.',
      'safetyReasonLimitedData':
          'सत्यापित लाइव्ह परिसर डेटा मर्यादित आहे — येथे अतिरिक्त सजग राहा.',
      'routeVerdictChanged': 'मार्ग बदलला',
      'routeVerdictChangedSummary':
          'तुम्ही नेहमीच्या मार्गापासून वळला आहात. तुम्ही सुरक्षित आहात याची खात्री करा.',
      'routeVerdictLearning': 'मार्ग शिकत आहे',
      'routeVerdictLearningSummary':
          'दैनंदिन मार्ग सुरक्षा तुमचे प्रवास पॅटर्न लाइव्ह GPS वरून शिकत आहे.',
      'routeVerdictOnTrack': 'नेहमीच्या मार्गावर',
      'routeVerdictOnTrackSummary':
          'तुम्ही तुमच्या शिकलेल्या सुरक्षित दैनंदिन मार्गावर आहात.',
      'routeVerdictCaution': 'मार्ग सावधानी',
      'routeVerdictCautionSummary':
          'काही मार्ग परिस्थितींवर आता अतिरिक्त लक्ष देणे आवश्यक आहे.',
      'routeVerdictAlert': 'मार्ग सतर्कता',
      'routeVerdictAlertSummary':
          'तुमचा सध्याचा मार्ग तुमच्या नेहमीच्या सुरक्षित पॅटर्नशी जुळत नाही.',
      'refresh': 'रीफ्रेश',
      'openMap': 'नकाशा उघडा',
      'resetHomeWorkplaceRouteLearning': 'घर-कार्यस्थळ मार्ग शिकणे रीसेट करा',
      'homeWorkplaceRouteLearningReset': 'घर-कार्यस्थळ मार्ग शिकणे रीसेट झाले.',
      'safetyCheckEndsIn': 'सुरक्षा तपासणी इतक्यात संपेल',
      'unlessYouConfirm': 'जोपर्यंत तुम्ही पुष्टी करत नाही.',
      'imSafe': 'मी सुरक्षित आहे',
      'pleaseFillAllRequiredDetails': 'कृपया सर्व आवश्यक तपशील भरा.',
      'complaintSubmittedSuccessfully': 'तक्रार यशस्वीरित्या सबमिट केली.',
      'submissionFailedTryAgain':
          'सबमिशन अयशस्वी झाले. कृपया पुन्हा प्रयत्न करा.',
      'openDetailedPoshActGuide': 'तपशीलवार POSH कायदा मार्गदर्शक उघडा',
      'clearPreviousQuizToUnlockThisLevel':
          'हा स्तर अनलॉक करण्यासाठी मागील क्विझ साफ करा.',
      'previous': 'मागील',
      'retryQuiz': 'क्विझ पुन्हा प्रयत्न करा',
      'pleaseAnswerEveryQuestionFirst':
          'कृपया आधी प्रत्येक प्रश्नाचे उत्तर द्या.',
      'pleaseAnswerThisQuestionBeforeContinuing':
          'कृपया पुढे जाण्यापूर्वी या प्रश्नाचे उत्तर द्या.',
      'currentLevel': 'सध्याचा स्तर',
      'detailedPoshActGuide': 'तपशीलवार POSH कायदा मार्गदर्शक',
      'cyberLawHubTitle': 'सायबर गुन्हे कायदा ग्रंथालय',
      'cyberLawHubSubtitle': 'आपले हक्क जाणा. कायदा जाणा. लढायला शिका.',
      'cyberLawHelplineTitle': 'आपातकालीन हेल्पलाइन',
      'cyberLawHelplineDesc': 'सायबर क्राइम: 1930  |  महिला: 181  |  बाल: 1098  |  पोलिस: 112',
      'cyberLawOverviewHeader': 'आढावा',
      'cyberLawActsHeader': 'लागू कायदे व कलमे',
      'cyberLawPunishmentHeader': 'कायदेशीर शिक्षा',
      'cyberLawWhatToDoHeader': 'तुम्ही पीडित असाल तर काय करावे',
      'cyberLawReportHeader': 'तक्रार कुठे करावी',
    },
  };

  String t(String key) {
    final langCode = _languageCodeFor(locale);
    return _values[langCode]?[key] ?? _values['en']![key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
