import 'package:flutter/widgets.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('en'));
  }

  static const supportedLocales = [Locale('en'), Locale('hi'), Locale('mr')];

  static String _languageCodeFor(Locale locale) {
    final normalizedCode = locale.languageCode.toLowerCase();
    return supportedLocales.any((item) => item.languageCode == normalizedCode)
        ? normalizedCode
        : 'en';
  }

  static const Map<String, Map<String, String>> _values = {
    'en': {
      'appTitle': 'Suraksha',
      'myProfile': 'My Profile',
      'profileSubtitle':
          'Manage your safety identity, language, and emergency readiness.',
      'profileOverview': 'Profile Overview',
      'profileStatsTitle': 'Your safety snapshot',
      'profileHeroCta': 'Personalize your profile for faster emergency support.',
      'languageSelectionTitle': 'Choose app language',
      'darkMode': 'Dark Mode',
      'darkModeSubtitleOn': 'Dark Bluish Theme',
      'darkModeSubtitleOff': 'Soft Calm Light Theme',
      'language': 'Language',
      'contentLanguage': 'Content language for the app',
      'english': 'English',
      'hindi': 'Hindi',
      'marathi': 'Marathi',
      'editProfile': 'Edit Profile',
      'editPhoneNumber': 'Edit Phone Number',
      'addEmergencyContactTitle': 'Add Emergency Contact',
      'editEmergencyContactTitle': 'Edit Emergency Contact',
      'editProfileDetails': 'EDIT PROFILE DETAILS',
      'editMedicalProfile': 'EDIT MEDICAL PROFILE',
      'fullName': 'Full Name',
      'email': 'Email',
      'phone': 'Phone Number',
      'relation': 'Relation',
      'name': 'Name',
      'bloodGroup': 'Blood Group',
      'allergies': 'Allergies',
      'medicalConditions': 'Medical Conditions',
      'currentMedications': 'Current Medications',
      'phoneNumber': 'Phone Number',
      'notProvided': 'Not provided',
      'emergencyContacts': 'Emergency Contacts',
      'contactsSaved': 'Contacts Saved',
      'emergencyContactList': 'Emergency Contact List',
      'addEmergencyContact': 'ADD EMERGENCY CONTACT',
      'addNewContact': 'Add new contact',
      'logoutSession': 'LOGOUT SESSION',
      'save': 'Save',
      'cancel': 'Cancel',
      'ok': 'OK',
      'saving': 'Saving...',
      'saved': 'Saved',
      'screamDetection': 'Scream Detection',
      'screamDetectionEnabled': 'Scream detection enabled.',
      'screamDetectionDisabled': 'Scream detection disabled.',
      'screamDetectionEnableFailed': 'Could not enable scream detection.',
      'microphoneSafetyMonitorActive': 'Microphone safety monitor is active.',
      'microphoneSafetyMonitorInactive': 'Microphone stays off while this is disabled.',
      'impactDetection': 'Impact Detection',
      'impactDetectionEnabled': 'Impact detection enabled.',
      'impactDetectionDisabled': 'Impact detection disabled.',
      'impactDetectionEnableFailed': 'Could not enable impact detection.',
      'motionSensorsActive': 'Motion sensors are watching for sudden impact.',
      'motionSensorsInactive': 'Motion sensors stay off while this is disabled.',
      'phoneNumberRequired': 'Phone number is required.',
      'nameAndPhoneRequired': 'Name and phone number are required.',
      'duplicatePhoneNumber': 'This phone number is already saved.',
      'savedLocallyRetryLater': 'Saved locally. Server sync will retry later.',
      'photoSavedLocally': 'Photo saved locally.',
      'serverSyncWillRetryLater': 'Server sync will retry later.',
      'profileSavedTitle': 'Profile saved',
      'profileSavedMessage': 'Your information is now stored and ready to use.',
      'medicalSavedTitle': 'Medical profile saved',
      'medicalSavedMessage':
          'Your medical details have been updated successfully.',
      'contactSavedTitle': 'Contact saved',
      'contactSavedMessage':
          'Emergency contact details were updated successfully.',
      'draftSavedTitle': 'Draft saved',
      'draftSavedMessage':
          'Your draft has been stored locally on this device.',
      'emergencyServices': 'Emergency Services',
      'communityAlerts': 'Community Alerts',
      'tapForAlerts': 'Tap for alerts',
      'tapRefreshTryAgain': 'Tap refresh to try again',
      'loadingLiveAreaAlerts': 'Loading live area alerts...',
      'checkingTrafficTransportNearbyActivity': 'Checking traffic, transport and nearby activity',
      'liveAlertsWillAppearHere': 'Live alerts will appear here',
      'keepGpsOnForRealtimeCommunityUpdates': 'Keep GPS on for realtime community updates',
      'womenHelpline': 'Women Helpline',
      'nearbyServices': 'Nearby Services',
      'nearbyHospitals': 'Nearby Hospitals',
      'policeStations': 'Police Stations',
      'nearbyWashrooms': 'Nearby Washrooms',
      'nearbyBloodBanks': 'Nearby Blood Banks',
      'tapToLoadNearby': 'Tap a button to load nearby real-time services.',
      'noNearbyPlaces': 'No nearby places found in 5 km radius.',
      'safeZoneActive': 'Prioritizing your Safety',
      'helloKaveri': 'Hello, Kaveri',
      'openSafetyMap': 'Open Safety Map',
      'openSafetyMapConfirm': 'Want to see this location on the map?',
      'yes': 'Yes',
      'no': 'No',
      'couldNotOpenDialer': 'Could not open dialer',
      'safeZoneUpdatedNearby': 'Safe zone updated nearby',
      'crowdedAreaWarning': 'Crowded area warning',
      'minsAgo2': '2 mins ago',
      'minsAgo15': '15 mins ago',
      'map': 'Map',
      'medical': 'Medical',
      'cyber': 'Cyber',
      'poshPortal': 'POSH Portal',
      'study': 'Study',
      'quizzes': 'Quizzes',
      'complaint': 'Complaint',
      'poshActLearningHub': 'POSH Act Learning Hub',
      'studyFirst': 'Study first',
      'readAllSectionsBeforeQuiz1': 'Read all sections before Quiz 1',
      'threeLevels': 'Three levels',
      'twentyMcqsEachQuiz': '20 MCQs in each quiz',
      'quizCertificationTrack': 'Quiz Certification Track',
      'studyFirstThenClearQuizzesInOrder': 'Study first, then clear the quizzes in order.',
      'level': 'Level',
      'levelPassed': 'Level Passed',
      'passed': 'Passed',
      'available': 'Available',
      'locked': 'Locked',
      'submitQuiz': 'Submit quiz',
      'next': 'Next',
      'unlocked': 'Unlocked',
      'quizNotClearedYet': 'Quiz not cleared yet',
      'reviewStudy': 'Review study',
      'retry': 'Retry',
      'viewCertificate': 'View certificate',
      'continueLabel': 'Continue',
      'poshCertified': 'POSH Certified',
      'fileWorkplaceComplaint': 'File Workplace Complaint',
      'fileWorkplaceComplaintSubtitle':
          'Prepare and submit a detailed complaint record. In immediate danger, call 112 first.',
      'keepRecordsFactual':
          'Keep your records factual and attach evidence when possible.',
      'yourFullName': 'Your Full Name',
      'yourPhoneNumber': 'Your Phone Number',
      'yourEmailAddress': 'Your Email Address',
      'accusedPersonName': 'Accused Person Name',
      'companyWorkplaceName': 'Company / Workplace Name',
      'incidentDateDdMmYyyy': 'Incident Date (DD/MM/YYYY)',
      'incidentLocation': 'Incident Location',
      'witnessesIfAny': 'Witnesses (if any)',
      'detailedIncidentDescription': 'Detailed Incident Description',
      'submitting': 'Submitting...',
      'submitComplaint': 'SUBMIT COMPLAINT',
      'guideIntro':
          'This guide is educational and operational. It explains process, boundaries, documentation, and escalation under the POSH framework in India.',
      'legalDisclaimer':
          'Legal Disclaimer: This guide is not a substitute for case-specific legal advice. For critical matters, consult a qualified lawyer, HR-POSH expert, or competent authority.',
      'guide1Title': '1. Background And Objective',
      'guide1Body':
          'The POSH Act creates a legal framework to prevent and address sexual harassment at work while protecting dignity and safe working conditions.',
      'guide2Title': '2. Where It Applies',
      'guide2Body':
          'It applies to public and private workplaces, schools, hospitals, NGOs, sports setups, domestic-work settings, and travel connected to employment.',
      'guide3Title': '3. Who Is Protected',
      'guide3Body':
          'The law primarily protects women at the workplace, including employees, trainees, interns, volunteers, contract staff, and visitors in that context.',
      'guide4Title': '4. What Counts As Sexual Harassment',
      'guide4Body':
          'Unwelcome physical contact, sexual requests, sexual remarks, pornography, and other verbal, non-verbal, or digital conduct of a sexual nature can count.',
      'guide5Title': '5. Internal Committee (IC) Requirements',
      'guide5Body':
          'Workplaces with 10 or more employees must form an Internal Committee with the required composition, including a presiding officer and an external member.',
      'guide6Title': '6. Complaint Timeline And Format',
      'guide6Body':
          'Complaints are usually filed in writing within 3 months. They should include parties, dates, location, facts, witnesses, evidence, and the relief sought.',
      'guide7Title': '7. Conciliation And Inquiry',
      'guide7Body':
          'Conciliation is voluntary. If it does not happen, the IC runs a fair inquiry where both sides are heard and the process stays written and documented.',
      'guide8Title': '8. Interim Relief During Proceedings',
      'guide8Body':
          'Interim relief can include transfer, leave, reporting-line changes, no-contact directions, work-from-home changes, or security support.',
      'guide9Title': '9. Inquiry Outcome And Employer Action',
      'guide9Body':
          'If proven, the IC can recommend action such as warning, apology, counseling, promotion impact, termination, or compensation according to service rules.',
      'guide10Title': '10. Police Complaint And Criminal Law',
      'guide10Body':
          'POSH does not replace criminal remedies. If the facts show a criminal offense, the complainant can also file a police complaint or FIR.',
      'guide11Title': '11. Confidentiality Rules',
      'guide11Body':
          'The identities of parties and witnesses, inquiry details, findings, and actions should stay confidential unless the law requires disclosure.',
      'guide12Title': '12. False Complaints: Correct Legal Position',
      'guide12Body':
          'A complaint is not automatically malicious just because it was not proven. Deliberate falsehood or forged evidence is a different standard.',
      'guide13Title': '13. How Not To Misuse The Act',
      'guide13Body':
          'Do not fabricate allegations, tamper with evidence, coach witnesses, or use the process for unrelated personal disputes.',
      'guide14Title': '14. Employer Compliance Checklist',
      'guide14Body':
          'Employers should form the IC correctly, publish the POSH policy, train staff, display the complaint channel, document inquiries, and avoid retaliation.',
      'guide15Title': '15. Practical Evidence Checklist',
      'guide15Body':
          'Preserve chats, emails, call logs, timestamps, witness names, complaint history, and relevant medical or mental-health records.',
      'guide16Title': '16. Appeals And Further Remedies',
      'guide16Body':
          'Depending on the rules and law, parties may challenge outcomes through appellate channels or seek external legal remedies.',
      'guide17Title': '17. Good-Faith Use Of POSH Portal',
      'guide17Body':
          'Use the portal to create records, file structured complaints, and prepare for IC or police processes. In danger, call emergency services first.',
      'safeRouteChanged': 'Safe route changed',
      'dailyRouteGuard': 'Daily Route Guard',
      'refresh': 'Refresh',
      'openMap': 'Open map',
      'resetHomeWorkplaceRouteLearning': 'Reset home-workplace route learning',
      'homeWorkplaceRouteLearningReset': 'Home-workplace route learning reset.',
      'safetyCheckEndsIn': 'Safety check ends in',
      'unlessYouConfirm': 'unless you confirm.',
      'imSafe': 'I am safe',
      'pleaseFillAllRequiredDetails': 'Please fill all required details.',
      'complaintSubmittedSuccessfully': 'Complaint submitted successfully.',
      'submissionFailedTryAgain': 'Submission failed. Please try again.',
      'openDetailedPoshActGuide': 'OPEN DETAILED POSH ACT GUIDE',
      'clearPreviousQuizToUnlockThisLevel': 'Clear the previous quiz to unlock this level.',
      'previous': 'Previous',
      'retryQuiz': 'Retry quiz',
      'pleaseAnswerEveryQuestionFirst': 'Please answer every question first.',
      'detailedPoshActGuide': 'Detailed POSH Act Guide',
    },
    'hi': {
      'appTitle': 'सुरक्षा',
      'myProfile': 'मेरा प्रोफाइल',
      'profileSubtitle':
          'अपनी सुरक्षा पहचान, भाषा और आपातकालीन तैयारी संभालें।',
      'profileOverview': 'प्रोफाइल सारांश',
      'profileStatsTitle': 'आपकी सुरक्षा झलक',
      'profileHeroCta': 'तेज़ सहायता के लिए प्रोफाइल को निजी बनाएं।',
      'languageSelectionTitle': 'ऐप भाषा चुनें',
      'darkMode': 'डार्क मोड',
      'darkModeSubtitleOn': 'डार्क ब्लू थीम',
      'darkModeSubtitleOff': 'हल्की शांत थीम',
      'language': 'भाषा',
      'contentLanguage': 'ऐप की सामग्री की भाषा',
      'english': 'अंग्रेज़ी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'editProfile': 'प्रोफाइल संपादित करें',
      'editPhoneNumber': 'फोन नंबर संपादित करें',
      'addEmergencyContactTitle': 'आपातकालीन संपर्क जोड़ें',
      'editEmergencyContactTitle': 'आपातकालीन संपर्क संपादित करें',
      'editProfileDetails': 'प्रोफाइल विवरण संपादित करें',
      'editMedicalProfile': 'मेडिकल प्रोफाइल संपादित करें',
      'fullName': 'पूरा नाम',
      'email': 'ईमेल',
      'phone': 'फोन नंबर',
      'relation': 'संबंध',
      'name': 'नाम',
      'bloodGroup': 'ब्लड ग्रुप',
      'allergies': 'एलर्जी',
      'medicalConditions': 'चिकित्सीय स्थितियां',
      'currentMedications': 'वर्तमान दवाएं',
      'phoneNumber': 'फोन नंबर',
      'notProvided': 'उपलब्ध नहीं',
      'emergencyContacts': 'आपातकालीन संपर्क',
      'contactsSaved': 'संपर्क सहेजे गए',
      'emergencyContactList': 'आपातकालीन संपर्क सूची',
      'addEmergencyContact': 'आपातकालीन संपर्क जोड़ें',
      'addNewContact': 'नया संपर्क जोड़ें',
      'logoutSession': 'लॉगआउट',
      'save': 'सहेजें',
      'cancel': 'रद्द करें',
      'ok': 'ठीक है',
      'saving': 'सहेजा जा रहा है...',
      'saved': 'सहेजा गया',
      'screamDetection': 'चीख पहचान',
      'screamDetectionEnabled': 'चीख पहचान चालू की गई।',
      'screamDetectionDisabled': 'चीख पहचान बंद की गई।',
      'screamDetectionEnableFailed': 'चीख पहचान चालू नहीं की जा सकी।',
      'microphoneSafetyMonitorActive': 'माइक्रोफोन सुरक्षा मॉनिटर चालू है।',
      'microphoneSafetyMonitorInactive': 'यह बंद रहने पर माइक्रोफोन बंद रहता है।',
      'impactDetection': 'झटका पहचान',
      'impactDetectionEnabled': 'झटका पहचान चालू की गई।',
      'impactDetectionDisabled': 'झटका पहचान बंद की गई।',
      'impactDetectionEnableFailed': 'झटका पहचान चालू नहीं की जा सकी।',
      'motionSensorsActive': 'मोशन सेंसर अचानक झटके पर नज़र रख रहे हैं।',
      'motionSensorsInactive': 'यह बंद रहने पर मोशन सेंसर बंद रहते हैं।',
      'phoneNumberRequired': 'फोन नंबर आवश्यक है।',
      'nameAndPhoneRequired': 'नाम और फोन नंबर आवश्यक हैं।',
      'duplicatePhoneNumber': 'यह फोन नंबर पहले से सहेजा गया है।',
      'savedLocallyRetryLater': 'स्थानीय रूप से सहेजा गया। सर्वर सिंक बाद में फिर से कोशिश करेगा।',
      'photoSavedLocally': 'फ़ोटो स्थानीय रूप से सहेजी गई।',
      'serverSyncWillRetryLater': 'सर्वर सिंक बाद में फिर से कोशिश करेगा।',
      'profileSavedTitle': 'प्रोफाइल सहेजा गया',
      'profileSavedMessage': 'आपकी जानकारी सुरक्षित रूप से सहेज ली गई है।',
      'medicalSavedTitle': 'मेडिकल प्रोफाइल सहेजा गया',
      'medicalSavedMessage': 'आपकी मेडिकल जानकारी सफलतापूर्वक अपडेट हो गई है।',
      'contactSavedTitle': 'संपर्क सहेजा गया',
      'contactSavedMessage': 'आपातकालीन संपर्क विवरण सफलतापूर्वक अपडेट हो गए।',
      'draftSavedTitle': 'ड्राफ्ट सहेजा गया',
      'draftSavedMessage': 'आपका ड्राफ्ट इस डिवाइस पर सुरक्षित कर लिया गया है।',
      'emergencyServices': 'आपातकालीन सेवाएं',
      'communityAlerts': 'समुदाय अलर्ट',
      'tapForAlerts': 'अलर्ट देखने के लिए टैप करें',
      'tapRefreshTryAgain': 'फिर कोशिश के लिए रिफ्रेश टैप करें',
      'loadingLiveAreaAlerts': 'लाइव क्षेत्र अलर्ट लोड हो रहे हैं...',
      'checkingTrafficTransportNearbyActivity': 'ट्रैफ़िक, परिवहन और आसपास की गतिविधि जाँच रहे हैं',
      'liveAlertsWillAppearHere': 'लाइव अलर्ट यहाँ दिखेंगे',
      'keepGpsOnForRealtimeCommunityUpdates': 'रीयलटाइम community updates के लिए GPS चालू रखें',
      'womenHelpline': 'महिला हेल्पलाइन',
      'nearbyServices': 'नज़दीकी सेवाएं',
      'nearbyHospitals': 'नज़दीकी अस्पताल',
      'policeStations': 'पुलिस स्टेशन',
      'nearbyWashrooms': 'नज़दीकी वॉशरूम',
      'nearbyBloodBanks': 'नज़दीकी ब्लड बैंक',
      'tapToLoadNearby': 'नज़दीकी सेवाएं लोड करने के लिए बटन दबाएं।',
      'noNearbyPlaces': '5 किमी के दायरे में कोई स्थान नहीं मिला।',
      'safeZoneActive': 'सुरक्षा प्राथमिकता',
      'helloKaveri': 'नमस्ते, कावेरी',
      'openSafetyMap': 'सुरक्षा मानचित्र खोलें',
      'openSafetyMapConfirm': 'क्या आप यह स्थान मानचित्र पर देखना चाहते हैं?',
      'yes': 'हाँ',
      'no': 'नहीं',
      'couldNotOpenDialer': 'डायलर नहीं खुल सका',
      'safeZoneUpdatedNearby': 'नज़दीक सुरक्षित क्षेत्र अपडेट हुआ',
      'crowdedAreaWarning': 'भीड़भाड़ क्षेत्र चेतावनी',
      'minsAgo2': '2 मिनट पहले',
      'minsAgo15': '15 मिनट पहले',
      'map': 'मैप',
      'medical': 'मेडिकल',
      'cyber': 'साइबर',
      'poshPortal': 'पॉश पोर्टल',
      'study': 'अध्ययन',
      'quizzes': 'क्विज़',
      'complaint': 'शिकायत',
      'poshActLearningHub': 'POSH अधिनियम अध्ययन केंद्र',
      'studyFirst': 'पहले अध्ययन करें',
      'readAllSectionsBeforeQuiz1': 'क्विज़ 1 से पहले सभी अनुभाग पढ़ें',
      'threeLevels': 'तीन स्तर',
      'twentyMcqsEachQuiz': 'हर क्विज़ में 20 MCQ',
      'quizCertificationTrack': 'क्विज़ प्रमाणन ट्रैक',
      'studyFirstThenClearQuizzesInOrder': 'पहले अध्ययन करें, फिर क्विज़ को क्रम से पूरा करें।',
      'level': 'स्तर',
      'levelPassed': 'स्तर पास',
      'passed': 'पास',
      'available': 'उपलब्ध',
      'locked': 'लॉक्ड',
      'submitQuiz': 'क्विज़ सबमिट करें',
      'next': 'अगला',
      'unlocked': 'अनलॉक्ड',
      'quizNotClearedYet': 'क्विज़ अभी साफ़ नहीं हुआ है',
      'reviewStudy': 'अध्ययन देखें',
      'retry': 'फिर से प्रयास करें',
      'viewCertificate': 'प्रमाणपत्र देखें',
      'continueLabel': 'जारी रखें',
      'poshCertified': 'POSH प्रमाणित',
      'fileWorkplaceComplaint': 'कार्यस्थल शिकायत दर्ज करें',
      'fileWorkplaceComplaintSubtitle':
          'विस्तृत शिकायत रिकॉर्ड तैयार करें और भेजें। तुरंत खतरे में 112 पर कॉल करें।',
      'keepRecordsFactual': 'अपने रिकॉर्ड तथ्यात्मक रखें और संभव हो तो साक्ष्य जोड़ें।',
      'yourFullName': 'आपका पूरा नाम',
      'yourPhoneNumber': 'आपका फोन नंबर',
      'yourEmailAddress': 'आपका ईमेल पता',
      'accusedPersonName': 'आरोपी व्यक्ति का नाम',
      'companyWorkplaceName': 'कंपनी / कार्यस्थल का नाम',
      'incidentDateDdMmYyyy': 'घटना की तारीख (DD/MM/YYYY)',
      'incidentLocation': 'घटना का स्थान',
      'witnessesIfAny': 'गवाह (यदि कोई हों)',
      'detailedIncidentDescription': 'घटना का विस्तृत विवरण',
      'submitting': 'सबमिट किया जा रहा है...',
      'submitComplaint': 'शिकायत सबमिट करें',
      'guideIntro':
          'यह मार्गदर्शिका शिक्षण और संचालन के लिए है। यह भारत में POSH ढांचे के तहत प्रक्रिया, सीमाएं, दस्तावेजीकरण और आगे की कार्रवाई समझाती है।',
      'legalDisclaimer':
          'कानूनी अस्वीकरण: यह मार्गदर्शिका मामले-विशेष कानूनी सलाह का विकल्प नहीं है। महत्वपूर्ण मामलों में योग्य वकील, HR-POSH विशेषज्ञ या सक्षम प्राधिकारी से सलाह लें।',
      'guide1Title': '1. पृष्ठभूमि और उद्देश्य',
      'guide1Body':
          'POSH अधिनियम काम पर यौन उत्पीड़न को रोकने और संबोधित करने के लिए कानूनी ढांचा बनाता है और गरिमा व सुरक्षित कार्य स्थितियों की रक्षा करता है।',
      'guide2Title': '2. यह कहाँ लागू होता है',
      'guide2Body':
          'यह सार्वजनिक और निजी कार्यस्थलों, स्कूलों, अस्पतालों, NGO, खेल सेटअप, घरेलू काम और रोजगार से जुड़े सफर पर लागू होता है।',
      'guide3Title': '3. कौन संरक्षित है',
      'guide3Body':
          'यह कानून मुख्य रूप से कार्यस्थल पर महिलाओं की रक्षा करता है, जिसमें कर्मचारी, प्रशिक्षु, इंटर्न, स्वयंसेवक, संविदा कर्मचारी और उस संदर्भ में आने वाले आगंतुक शामिल हैं।',
      'guide4Title': '4. यौन उत्पीड़न क्या है',
      'guide4Body':
          'अवांछित शारीरिक संपर्क, यौन अनुरोध, यौन टिप्पणियाँ, अश्लील सामग्री, और यौन प्रकृति का अन्य मौखिक, गैर-मौखिक या डिजिटल आचरण इसमें आ सकते हैं।',
      'guide5Title': '5. आंतरिक समिति (IC) आवश्यकताएँ',
      'guide5Body':
          '10 या अधिक कर्मचारियों वाले कार्यस्थलों में आवश्यक संरचना के साथ Internal Committee बननी चाहिए, जिसमें Presiding Officer और बाहरी सदस्य शामिल हों।',
      'guide6Title': '6. शिकायत समयसीमा और प्रारूप',
      'guide6Body':
          'शिकायत आमतौर पर 3 महीने के भीतर लिखित रूप में दी जाती है। इसमें पक्ष, तिथियाँ, स्थान, तथ्य, गवाह, साक्ष्य और मांगी गई राहत शामिल होनी चाहिए।',
      'guide7Title': '7. सुलह और जाँच',
      'guide7Body':
          'सुलह स्वैच्छिक है। यदि ऐसा न हो, तो IC निष्पक्ष जाँच करती है जहाँ दोनों पक्ष सुने जाते हैं और प्रक्रिया लिखित व दस्तावेजित रहती है।',
      'guide8Title': '8. प्रक्रिया के दौरान अंतरिम राहत',
      'guide8Body':
          'अंतरिम राहत में स्थानांतरण, अवकाश, रिपोर्टिंग लाइन परिवर्तन, संपर्क-निषेध निर्देश, WFH बदलाव या सुरक्षा सहायता शामिल हो सकती है।',
      'guide9Title': '9. जाँच परिणाम और नियोक्ता की कार्रवाई',
      'guide9Body':
          'यदि आरोप सिद्ध हों, तो IC नियमों के अनुसार चेतावनी, माफी, परामर्श, प्रमोशन/वेतन वृद्धि पर प्रभाव, बर्खास्तगी या मुआवज़ा सुझा सकती है।',
      'guide10Title': '10. पुलिस शिकायत और आपराधिक कानून',
      'guide10Body':
          'POSH आपराधिक उपायों की जगह नहीं लेता। यदि तथ्य अपराध दिखाते हैं, तो शिकायतकर्ता पुलिस शिकायत या FIR भी दर्ज कर सकता है।',
      'guide11Title': '11. गोपनीयता नियम',
      'guide11Body':
          'पक्षों और गवाहों की पहचान, जाँच विवरण, निष्कर्ष और कार्रवाई गोपनीय रखी जानी चाहिए, जब तक कानून अलग से न कहे।',
      'guide12Title': '12. झूठी शिकायत: सही कानूनी स्थिति',
      'guide12Body':
          'केवल साबित न होने से शिकायत अपने आप दुर्भावनापूर्ण नहीं हो जाती। जानबूझकर झूठ या जाली साक्ष्य अलग मानक है।',
      'guide13Title': '13. अधिनियम का दुरुपयोग कैसे न करें',
      'guide13Body':
          'जानबूझकर झूठे आरोप, साक्ष्य में छेड़छाड़, गवाहों को प्रभावित करना या निजी विवादों के लिए प्रक्रिया का उपयोग न करें।',
      'guide14Title': '14. नियोक्ता अनुपालन सूची',
      'guide14Body':
          'IC सही ढंग से बनाएं, POSH नीति प्रकाशित करें, स्टाफ को प्रशिक्षित करें, शिकायत चैनल दिखाएं, जाँच दस्तावेज़ रखें और प्रतिशोध से बचें।',
      'guide15Title': '15. व्यावहारिक साक्ष्य सूची',
      'guide15Body':
          'चैट, ईमेल, कॉल लॉग, टाइमस्टैम्प, गवाहों के नाम, शिकायत इतिहास और संबंधित मेडिकल/मेंटल हेल्थ रिकॉर्ड सुरक्षित रखें।',
      'guide16Title': '16. अपील और अन्य उपाय',
      'guide16Body':
          'नियमों और कानून के अनुसार, पक्ष अपीलीय मार्गों से परिणामों को चुनौती दे सकते हैं या बाहरी कानूनी उपाय खोज सकते हैं।',
      'guide17Title': '17. POSH पोर्टल का सद्भावपूर्ण उपयोग',
      'guide17Body':
          'रिकॉर्ड बनाने, संरचित शिकायत दाखिल करने और IC या पुलिस प्रक्रिया की तैयारी के लिए पोर्टल का उपयोग करें। खतरे में पहले आपातकालीन सहायता लें।',
      'safeRouteChanged': 'सुरक्षित मार्ग बदल गया',
      'dailyRouteGuard': 'दैनिक मार्ग सुरक्षा',
      'refresh': 'रीफ़्रेश',
      'openMap': 'मानचित्र खोलें',
      'resetHomeWorkplaceRouteLearning': 'घर-कार्यस्थल मार्ग सीखना रीसेट करें',
      'homeWorkplaceRouteLearningReset': 'घर-कार्यस्थल मार्ग सीखना रीसेट हो गया।',
      'safetyCheckEndsIn': 'सुरक्षा जांच समाप्त होगी',
      'unlessYouConfirm': 'जब तक आप पुष्टि नहीं करते।',
      'imSafe': 'मैं सुरक्षित हूँ',
      'pleaseFillAllRequiredDetails': 'कृपया सभी आवश्यक विवरण भरें।',
      'complaintSubmittedSuccessfully': 'शिकायत सफलतापूर्वक सबमिट की गई।',
      'submissionFailedTryAgain': 'सबमिशन विफल रहा। कृपया पुनः प्रयास करें।',
      'openDetailedPoshActGuide': 'विस्तृत POSH अधिनियम मार्गदर्शिका खोलें',
      'clearPreviousQuizToUnlockThisLevel': 'इस स्तर को अनलॉक करने के लिए पिछला क्विज़ साफ़ करें।',
      'previous': 'पिछला',
      'retryQuiz': 'क्विज़ फिर से प्रयास करें',
      'pleaseAnswerEveryQuestionFirst': 'कृपया पहले हर प्रश्न का उत्तर दें।',
      'detailedPoshActGuide': 'विस्तृत POSH अधिनियम मार्गदर्शिका',
    },
    'mr': {
      'appTitle': 'सुरक्षा',
      'myProfile': 'माझे प्रोफाइल',
      'profileSubtitle':
          'तुमची सुरक्षा ओळख, भाषा आणि आपत्कालीन तयारी सांभाळा.',
      'profileOverview': 'प्रोफाइल सारांश',
      'profileStatsTitle': 'तुमचा सुरक्षा स्नॅपशॉट',
      'profileHeroCta': 'जलद मदतीसाठी प्रोफाइल वैयक्तिक बनवा.',
      'languageSelectionTitle': 'अॅपची भाषा निवडा',
      'darkMode': 'डार्क मोड',
      'darkModeSubtitleOn': 'डार्क ब्लू थीम',
      'darkModeSubtitleOff': 'हलकी शांत थीम',
      'language': 'भाषा',
      'contentLanguage': 'अॅपमधील मजकुराची भाषा',
      'english': 'इंग्रजी',
      'hindi': 'हिंदी',
      'marathi': 'मराठी',
      'editProfile': 'प्रोफाइल संपादित करा',
      'editPhoneNumber': 'फोन नंबर संपादित करा',
      'addEmergencyContactTitle': 'आपत्कालीन संपर्क जोडा',
      'editEmergencyContactTitle': 'आपत्कालीन संपर्क संपादित करा',
      'editProfileDetails': 'प्रोफाइल तपशील संपादित करा',
      'editMedicalProfile': 'मेडिकल प्रोफाइल संपादित करा',
      'fullName': 'पूर्ण नाव',
      'email': 'ईमेल',
      'phone': 'फोन नंबर',
      'relation': 'नाते',
      'name': 'नाव',
      'bloodGroup': 'ब्लड ग्रुप',
      'allergies': 'अॅलर्जी',
      'medicalConditions': 'आरोग्यविषयक स्थिती',
      'currentMedications': 'सध्याची औषधे',
      'phoneNumber': 'फोन नंबर',
      'notProvided': 'उपलब्ध नाही',
      'emergencyContacts': 'आपत्कालीन संपर्क',
      'contactsSaved': 'संपर्क जतन केले',
      'emergencyContactList': 'आपत्कालीन संपर्क यादी',
      'addEmergencyContact': 'आपत्कालीन संपर्क जोडा',
      'addNewContact': 'नवीन संपर्क जोडा',
      'logoutSession': 'लॉगआउट',
      'save': 'जतन करा',
      'cancel': 'रद्द करा',
      'ok': 'ठीक आहे',
      'saving': 'जतन करत आहे...',
      'saved': 'जतन झाले',
      'screamDetection': 'चिघाड ओळख',
      'screamDetectionEnabled': 'चिघाड ओळख सुरू केली.',
      'screamDetectionDisabled': 'चिघाड ओळख बंद केली.',
      'screamDetectionEnableFailed': 'चिघाड ओळख सुरू करता आली नाही.',
      'microphoneSafetyMonitorActive': 'मायक्रोफोन सुरक्षा मॉनिटर सुरू आहे.',
      'microphoneSafetyMonitorInactive': 'हे बंद असताना मायक्रोफोन बंद राहतो.',
      'impactDetection': 'आघात ओळख',
      'impactDetectionEnabled': 'आघात ओळख सुरू केली.',
      'impactDetectionDisabled': 'आघात ओळख बंद केली.',
      'impactDetectionEnableFailed': 'आघात ओळख सुरू करता आली नाही.',
      'motionSensorsActive': 'मोशन सेन्सर अचानक आघातासाठी लक्ष ठेवत आहेत.',
      'motionSensorsInactive': 'हे बंद असताना मोशन सेन्सर बंद राहतात.',
      'phoneNumberRequired': 'फोन नंबर आवश्यक आहे.',
      'nameAndPhoneRequired': 'नाव आणि फोन नंबर आवश्यक आहेत.',
      'duplicatePhoneNumber': 'हा फोन नंबर आधीच जतन केला आहे.',
      'savedLocallyRetryLater': 'स्थानिकरित्या जतन केले. सर्व्हर सिंक नंतर पुन्हा प्रयत्न करेल.',
      'photoSavedLocally': 'फोटो स्थानिकरित्या जतन केला.',
      'serverSyncWillRetryLater': 'सर्व्हर सिंक नंतर पुन्हा प्रयत्न करेल.',
      'profileSavedTitle': 'प्रोफाइल जतन झाले',
      'profileSavedMessage': 'तुमची माहिती सुरक्षितपणे जतन झाली आहे.',
      'medicalSavedTitle': 'मेडिकल प्रोफाइल जतन झाले',
      'medicalSavedMessage':
          'तुमची मेडिकल माहिती यशस्वीरित्या अपडेट झाली आहे.',
      'contactSavedTitle': 'संपर्क जतन झाला',
      'contactSavedMessage':
          'आपत्कालीन संपर्क तपशील यशस्वीरित्या अपडेट झाले आहेत.',
      'draftSavedTitle': 'ड्राफ्ट जतन झाला',
      'draftSavedMessage': 'तुमचा ड्राफ्ट या डिव्हाइसवर सुरक्षित झाला आहे.',
      'emergencyServices': 'आपत्कालीन सेवा',
      'communityAlerts': 'समुदाय सूचना',
      'tapForAlerts': 'अलर्ट पाहण्यासाठी टॅप करा',
      'tapRefreshTryAgain': 'पुन्हा प्रयत्न करण्यासाठी रिफ्रेश टॅप करा',
      'loadingLiveAreaAlerts': 'लाईव्ह परिसर अलर्ट लोड होत आहेत...',
      'checkingTrafficTransportNearbyActivity': 'वाहतूक, परिवहन आणि जवळची हालचाल तपासत आहोत',
      'liveAlertsWillAppearHere': 'लाईव्ह अलर्ट इथे दिसतील',
      'keepGpsOnForRealtimeCommunityUpdates': 'रीअलटाइम community updates साठी GPS चालू ठेवा',
      'womenHelpline': 'महिला हेल्पलाइन',
      'nearbyServices': 'जवळच्या सेवा',
      'nearbyHospitals': 'जवळची रुग्णालये',
      'policeStations': 'पोलीस ठाणे',
      'nearbyWashrooms': 'जवळचे वॉशरूम',
      'nearbyBloodBanks': 'जवळच्या रक्तपेढ्या',
      'tapToLoadNearby': 'जवळच्या सेवा लोड करण्यासाठी बटण दाबा.',
      'noNearbyPlaces': '5 किमी परिसरात कोणतीही जागा सापडली नाही.',
      'safeZoneActive': 'सुरक्षा प्राधान्य',
      'helloKaveri': 'नमस्कार, कावेरी',
      'openSafetyMap': 'सुरक्षा नकाशा उघडा',
      'openSafetyMapConfirm': 'हे ठिकाण नकाशावर पाहायचे आहे का?',
      'yes': 'हो',
      'no': 'नाही',
      'couldNotOpenDialer': 'डायलर उघडता आला नाही',
      'safeZoneUpdatedNearby': 'जवळ सुरक्षित क्षेत्र अपडेट झाले',
      'crowdedAreaWarning': 'गर्दीच्या भागाची चेतावणी',
      'minsAgo2': '2 मिनिटांपूर्वी',
      'minsAgo15': '15 मिनिटांपूर्वी',
      'map': 'नकाशा',
      'medical': 'मेडिकल',
      'cyber': 'सायबर',
      'poshPortal': 'POSH पोर्टल',
      'study': 'अभ्यास',
      'quizzes': 'क्विझ',
      'complaint': 'तक्रार',
      'poshActLearningHub': 'POSH कायदा अभ्यास केंद्र',
      'studyFirst': 'आधी अभ्यास करा',
      'readAllSectionsBeforeQuiz1': 'क्विझ 1 पूर्वी सर्व विभाग वाचा',
      'threeLevels': 'तीन स्तर',
      'twentyMcqsEachQuiz': 'प्रत्येक क्विझमध्ये 20 MCQ',
      'quizCertificationTrack': 'क्विझ प्रमाणपत्र ट्रॅक',
      'studyFirstThenClearQuizzesInOrder': 'आधी अभ्यास करा, मग क्विझ क्रमाने पूर्ण करा.',
      'level': 'स्तर',
      'levelPassed': 'स्तर पूर्ण',
      'passed': 'पूर्ण',
      'available': 'उपलब्ध',
      'locked': 'लॉक',
      'submitQuiz': 'क्विझ सबमिट करा',
      'next': 'पुढे',
      'unlocked': 'अनलॉक',
      'quizNotClearedYet': 'क्विझ अद्याप साफ झालेले नाही',
      'reviewStudy': 'अभ्यास पहा',
      'retry': 'पुन्हा प्रयत्न',
      'viewCertificate': 'प्रमाणपत्र पहा',
      'continueLabel': 'सुरू ठेवा',
      'poshCertified': 'POSH प्रमाणित',
      'fileWorkplaceComplaint': 'कार्यस्थळी तक्रार नोंदवा',
      'fileWorkplaceComplaintSubtitle':
          'तपशीलवार तक्रार नोंद तयार करा आणि पाठवा. तातडीच्या धोक्यात 112 वर कॉल करा.',
      'keepRecordsFactual': 'तुमची नोंद तथ्यात्मक ठेवा आणि शक्य असल्यास पुरावा जोडा.',
      'yourFullName': 'तुमचे पूर्ण नाव',
      'yourPhoneNumber': 'तुमचा फोन नंबर',
      'yourEmailAddress': 'तुमचा ईमेल पत्ता',
      'accusedPersonName': 'आरोपी व्यक्तीचे नाव',
      'companyWorkplaceName': 'कंपनी / कार्यस्थळाचे नाव',
      'incidentDateDdMmYyyy': 'घटनेची तारीख (DD/MM/YYYY)',
      'incidentLocation': 'घटनेचे ठिकाण',
      'witnessesIfAny': 'साक्षीदार (असल्यास)',
      'detailedIncidentDescription': 'घटनेचे सविस्तर वर्णन',
      'submitting': 'सबमिट करत आहे...',
      'submitComplaint': 'तक्रार सबमिट करा',
      'guideIntro':
          'हे मार्गदर्शक शैक्षणिक आणि कार्यात्मक आहे. हे भारतातील POSH चौकटीतील प्रक्रिया, मर्यादा, दस्तऐवजीकरण आणि पुढील पावले समजावते.',
      'legalDisclaimer':
          'कायदेशीर अस्वीकरण: हे मार्गदर्शक केस-विशिष्ट कायदेशीर सल्ल्याचा पर्याय नाही. महत्त्वाच्या बाबींमध्ये पात्र वकील, HR-POSH तज्ज्ञ किंवा सक्षम प्राधिकरणाचा सल्ला घ्या.',
      'guide1Title': '1. पार्श्वभूमी आणि उद्देश',
      'guide1Body':
          'POSH कायदा कामाच्या ठिकाणी लैंगिक छळ रोखण्यासाठी आणि त्यावर कारवाई करण्यासाठी कायदेशीर चौकट तयार करतो आणि सन्मान व सुरक्षित कामाच्या अटींचे रक्षण करतो.',
      'guide2Title': '2. कुठे लागू होते',
      'guide2Body':
          'हे सार्वजनिक व खासगी कार्यस्थळे, शाळा, रुग्णालये, NGO, क्रीडा व्यवस्था, घरकामाचे संदर्भ आणि नोकरीशी संबंधित प्रवासावर लागू होते.',
      'guide3Title': '3. कोण संरक्षित आहे',
      'guide3Body':
          'हा कायदा मुख्यतः कार्यस्थळी महिलांचे संरक्षण करतो, ज्यात कर्मचारी, प्रशिक्षणार्थी, इंटर्न, स्वयंसेवक, करार कर्मचारी आणि त्या संदर्भातील अभ्यागत समाविष्ट आहेत.',
      'guide4Title': '4. लैंगिक छळ म्हणजे काय',
      'guide4Body':
          'अनाहूत शारीरिक संपर्क, लैंगिक मागण्या, लैंगिक टिप्पणी, अश्लील सामग्री आणि लैंगिक स्वरूपाचे इतर मौखिक, अमौखिक किंवा डिजिटल वर्तन यामध्ये येऊ शकते.',
      'guide5Title': '5. अंतर्गत समिती (IC) आवश्यकता',
      'guide5Body':
          '10 किंवा अधिक कर्मचारी असलेल्या कार्यस्थळी आवश्यक रचनेसह Internal Committee असणे बंधनकारक आहे, ज्यात Presiding Officer आणि बाह्य सदस्य असतो.',
      'guide6Title': '6. तक्रार वेळमर्यादा आणि स्वरूप',
      'guide6Body':
          'तक्रार सामान्यतः 3 महिन्यांच्या आत लेखी दिली जाते. त्यात पक्ष, तारखा, ठिकाण, तथ्ये, साक्षीदार, पुरावे आणि मागितलेली मदत असावी.',
      'guide7Title': '7. संमती/समेट आणि चौकशी',
      'guide7Body':
          'समेट स्वैच्छिक असतो. तो न झाल्यास IC निष्पक्ष चौकशी करते जिथे दोन्ही बाजू ऐकल्या जातात आणि प्रक्रिया लेखी व दस्तऐवजीकृत राहते.',
      'guide8Title': '8. प्रक्रियेतील अंतरिम मदत',
      'guide8Body':
          'अंतरिम मदतीमध्ये बदली, रजा, रिपोर्टिंग लाइन बदल, संपर्क-निषेध, WFH बदल किंवा सुरक्षा मदत समाविष्ट असू शकते.',
      'guide9Title': '9. चौकशी निकाल आणि नियोक्त्याची कारवाई',
      'guide9Body':
          'आरोप सिद्ध झाल्यास, नियमांनुसार इशारा, माफी, समुपदेशन, पदोन्नती/वाढीवर परिणाम, नोकरी समाप्ती किंवा भरपाई सुचवली जाऊ शकते.',
      'guide10Title': '10. पोलिस तक्रार आणि फौजदारी कायदा',
      'guide10Body':
          'POSH हे फौजदारी उपायांचा पर्याय नाही. तथ्यांमधून गुन्हा दिसल्यास, तक्रारदार पोलिस तक्रार किंवा FIR देखील दाखल करू शकतो.',
      'guide11Title': '11. गोपनीयता नियम',
      'guide11Body':
          'पक्ष आणि साक्षीदारांची ओळख, चौकशी तपशील, निष्कर्ष आणि कारवाई गोपनीय ठेवली पाहिजे, जोपर्यंत कायदा वेगळे सांगत नाही.',
      'guide12Title': '12. खोट्या तक्रारी: योग्य कायदेशीर स्थिती',
      'guide12Body':
          'फक्त सिद्ध न झाल्याने तक्रार आपोआप द्वेषपूर्ण ठरत नाही. जाणूनबुजून खोटेपणा किंवा बनावट पुरावा वेगळा निकष आहे.',
      'guide13Title': '13. कायद्याचा गैरवापर कसा करू नये',
      'guide13Body':
          'जाणूनबुजून खोटे आरोप, पुराव्यात फेरफार, साक्षीदारांना प्रभावित करणे किंवा वैयक्तिक वादांसाठी प्रक्रिया वापरणे टाळा.',
      'guide14Title': '14. नियोक्ता अनुपालन सूची',
      'guide14Body':
          'IC योग्यरित्या तयार करा, POSH धोरण प्रकाशित करा, स्टाफला प्रशिक्षण द्या, तक्रार चॅनेल दाखवा, जाँच दस्तऐवजीकरण ठेवा आणि सूड टाळा.',
      'guide15Title': '15. व्यावहारिक पुरावा सूची',
      'guide15Body':
          'चॅट, ईमेल, कॉल लॉग, टाइमस्टॅम्प, साक्षीदारांची नावे, तक्रार इतिहास आणि संबंधित वैद्यकीय/मानसिक आरोग्य नोंदी जपून ठेवा.',
      'guide16Title': '16. अपील आणि इतर उपाय',
      'guide16Body':
          'नियम आणि कायद्याप्रमाणे, पक्ष अपीलीय मार्गांद्वारे निकाल आव्हान देऊ शकतात किंवा बाह्य कायदेशीर उपाय शोधू शकतात.',
      'guide17Title': '17. POSH पोर्टलचा सद्भावपूर्ण वापर',
      'guide17Body':
          'रेकॉर्ड तयार करण्यासाठी, संरचित तक्रार दाखल करण्यासाठी आणि IC किंवा पोलिस प्रक्रियेची तयारी करण्यासाठी पोर्टल वापरा. धोक्यात आधी आपत्कालीन मदत घ्या.',
      'safeRouteChanged': 'सुरक्षित मार्ग बदलला',
      'dailyRouteGuard': 'दैनंदिन मार्ग सुरक्षा',
      'refresh': 'रीफ्रेश',
      'openMap': 'नकाशा उघडा',
      'resetHomeWorkplaceRouteLearning': 'घर-कार्यस्थळ मार्ग शिकणे रीसेट करा',
      'homeWorkplaceRouteLearningReset': 'घर-कार्यस्थळ मार्ग शिकणे रीसेट झाले.',
      'safetyCheckEndsIn': 'सुरक्षा तपासणी इतक्यात संपेल',
      'unlessYouConfirm': 'जोपर्यंत तुम्ही पुष्टी करत नाही.',
      'imSafe': 'मी सुरक्षित आहे',
      'pleaseFillAllRequiredDetails': 'कृपया सर्व आवश्यक तपशील भरा.',
      'complaintSubmittedSuccessfully': 'तक्रार यशस्वीरित्या सबमिट केली.',
      'submissionFailedTryAgain': 'सबमिशन अयशस्वी झाले. कृपया पुन्हा प्रयत्न करा.',
      'openDetailedPoshActGuide': 'तपशीलवार POSH कायदा मार्गदर्शक उघडा',
      'clearPreviousQuizToUnlockThisLevel': 'हा स्तर अनलॉक करण्यासाठी मागील क्विझ साफ करा.',
      'previous': 'मागील',
      'retryQuiz': 'क्विझ पुन्हा प्रयत्न करा',
      'pleaseAnswerEveryQuestionFirst': 'कृपया आधी प्रत्येक प्रश्नाचे उत्तर द्या.',
      'detailedPoshActGuide': 'तपशीलवार POSH कायदा मार्गदर्शक',
    },
  };

  String t(String key) {
    final langCode = _languageCodeFor(locale);
    return _values[langCode]?[key] ?? _values['en']![key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => AppLocalizations.supportedLocales.any(
    (item) => item.languageCode == locale.languageCode,
  );

  @override
  Future<AppLocalizations> load(Locale locale) async =>
      AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) =>
      false;
}
